---
sidebar: sidebar 
permalink: migration/migrate-vms-to-ec2-fsxn-overview.html 
keywords: netapp, vmware, amazon, ec2, fsxn, migration, iscsi, 
summary: '이 기술 보고서에서는 Cirrus Migrate Cloud(CMC)의 MigrateOps "데이터 모빌리티 코드" 기능을 사용하여 온프레미스 VMware vSphere VM을 FSx ONTAP iSCSI LUN에 배치된 데이터 디스크가 있는 Amazon EC2 인스턴스로 마이그레이션하는 방법을 다룹니다.' 
---
= Amazon FSx for ONTAP 을 사용하여 VM을 Amazon EC2로 마이그레이션하는 방법에 대해 알아보세요.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Amazon FSx for NetApp ONTAP 사용하면 스냅샷, 씬 프로비저닝, 복제와 같은 중요한 스토리지 기능을 유지하면서 VMware vSphere VM을 Amazon EC2로 쉽게 마이그레이션할 수 있습니다.  익숙한 도구와 프로토콜을 지원하여 마이그레이션 프로세스를 간소화하고 비용과 복잡성을 줄여줍니다.

조직에서는 Amazon Elastic Compute Cloud(Amazon EC2) 인스턴스 및 Amazon FSx for NetApp ONTAP (FSx ONTAP)과 같은 서비스를 활용하여 IT 인프라를 현대화하고 비용을 절감하며 운영 효율성을 개선함으로써 AWS의 클라우드 컴퓨팅 솔루션으로의 마이그레이션을 가속화하고 있습니다.  이러한 AWS 제품은 소비 기반 가격 책정 모델과 엔터프라이즈 스토리지 기능을 통해 총 소유 비용(TCO)을 최적화하는 마이그레이션을 지원하여 변화하는 글로벌 비즈니스 수요를 충족할 수 있는 유연성과 확장성을 제공합니다.



== 개요

VMware vSphere에 많은 투자를 한 기업의 경우, 현재 시장 상황을 고려하면 AWS로 마이그레이션하는 것은 비용 효율적인 옵션이며, 독특한 기회를 제공합니다.

이러한 조직은 AWS로 전환하면서 익숙한 기능 세트, 특히 스토리지 기능을 보존하는 동시에 클라우드의 민첩성과 비용상의 이점을 활용하고자 합니다.  워크로드를 마이그레이션하거나 재해 복구 솔루션을 설정할 때 익숙한 스토리지 프로토콜(특히 iSCSI), 프로세스, 도구 및 기술 세트를 사용하여 원활한 운영을 유지하는 것이 중요합니다.

AWS 관리형 스토리지 서비스 FSx ONTAP 을 사용하면 온프레미스에서 타사 공급업체의 스토리지 기능을 그대로 활용하여 AWS의 장점을 최대한 활용하면서 중단을 최소화하고 미래 투자를 극대화할 수 있습니다.

이 기술 보고서에서는 Cirrus Migrate Cloud(CMC)의 MigrateOps "데이터 이동성 코드" 기능을 사용하여 온프레미스 VMware vSphere VM을 FSx ONTAP iSCSI LUN에 배치된 데이터 디스크가 있는 Amazon EC2 인스턴스로 마이그레이션하는 방법을 다룹니다.



== 솔루션 요구 사항

현재 VMware 고객들은 여러 가지 과제를 해결하고자 노력하고 있습니다.  이러한 조직은 다음을 원합니다.

. 씬 프로비저닝, 스토리지 효율성 기술, 제로 풋프린트 복제, 통합 백업, 블록 수준 복제, 계층화와 같은 엔터프라이즈 스토리지 기능을 활용하세요.  이를 통해 AWS에서 마이그레이션 작업을 최적화하고 1일차부터 미래 지향적인 배포가 가능해집니다.
. FSx ONTAP 과 이 솔루션이 제공하는 비용 최적화 기능을 통합하여 현재 Amazon EC2 인스턴스를 사용하는 AWS의 스토리지 배포를 최적화합니다.
. 필요한 IOPS 및 처리량 매개변수를 충족하도록 Amazon EC2 인스턴스의 크기를 조정하여 블록 스토리지 솔루션과 함께 Amazon EC2 인스턴스를 사용할 때 발생하는 총 소유 비용(TCO)을 줄이세요.  블록 스토리지를 사용하면 Amazon EC2 디스크 작업의 대역폭과 I/O 속도에 제한이 있습니다.  FSx ONTAP 사용한 파일 저장은 네트워크 대역폭을 사용합니다.  즉, FSx ONTAP 에는 VM 수준의 I/O 제한이 없습니다.




== 기술 구성 요소 개요



=== FSx ONTAP 개념

Amazon FSx ONTAP 은 NetApp ONTAP 파일 시스템에 AWS의 모든 친숙한 ONTAP 데이터 관리 기능, 성능 및 API를 제공하는 완전 관리형 AWS 스토리지 서비스입니다.  고성능 스토리지는 여러 프로토콜(NFS, SMB, iSCSI)을 지원하여 Windows, Linux, macOS EC2 인스턴스를 사용하는 워크로드에 대한 단일 서비스를 제공합니다.

FSx ONTAP 은 ONTAP 파일 시스템이므로 SnapMirror 데이터 복제 기술, 씬 클론, NetApp Snapshot 복사본을 포함하여 다양한 익숙한 NetApp 기능과 서비스를 제공합니다.  FSx ONTAP 데이터 계층화를 통해 저비용 용량 계층을 활용함으로써 탄력성을 갖추고 사실상 무제한적인 규모에 도달할 수 있습니다.  또한 NetApp 고유한 스토리지 효율성 기술을 통해 AWS의 스토리지 비용을 한층 더 절감할 수 있습니다.  자세한 내용은 다음을 참조하세요.link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Amazon FSx ONTAP 시작하기"] .



==== 파일 시스템

FSx ONTAP 의 핵심 리소스는 SSD(Solid State Drive) 스토리지를 기반으로 하는 파일 시스템입니다.  FSx ONTAP 파일 시스템을 프로비저닝할 때 사용자는 원하는 처리량과 저장 용량을 입력하고 파일 시스템이 상주할 Amazon VPC를 선택합니다.

사용자는 파일 시스템에 대한 두 가지 기본 고가용성 배포 모델, 즉 다중 가용성 영역(AZ) 또는 단일 AZ 배포 중에서 선택할 수도 있습니다.  이러한 각 옵션은 내구성과 가용성 측면에서 고유한 수준을 제공하며, 고객은 사용 사례의 비즈니스 연속성 요구 사항에 따라 이를 선택할 수 있습니다.  다중 AZ 배포는 두 개의 AZ에 걸쳐 원활하게 복제되는 이중 노드로 구성됩니다.  비용에 더 최적화된 단일 AZ 배포 옵션은 두 개의 별도 장애 도메인으로 분할된 두 개의 노드로 파일 시스템을 구성하며, 두 도메인 모두 단일 AZ 내에 있습니다.



=== 스토리지 가상 머신

FSx ONTAP 파일 시스템의 데이터는 스토리지 가상 머신(SVM)이라고 하는 논리적 스토리지 파티션을 통해 액세스됩니다.  SVM은 실제로 자체 데이터 및 관리 액세스 포인트를 갖춘 자체 파일 서버입니다.  FSx ONTAP 파일 시스템의 iSCSI LUN에 액세스할 때 Amazon EC2 인스턴스는 SVM의 iSCSI 엔드포인트 IP 주소를 사용하여 SVM과 직접 인터페이스합니다.

클러스터에서 단일 SVM을 유지하는 것도 가능하지만, 클러스터에서 여러 SVM을 실행하는 옵션은 다양한 용도와 이점이 있습니다.  고객은 워크로드 격리 요구 사항을 포함한 비즈니스 요구 사항을 고려하여 구성할 최적의 SVM 수를 결정할 수 있습니다.



==== 볼륨

FSx ONTAP SVM 내의 데이터는 볼륨이라는 구조에 저장되고 구성되며, 볼륨은 가상 컨테이너 역할을 합니다.  개별 볼륨은 하나 또는 여러 개의 LUN으로 구성할 수 있습니다.  각 볼륨에 저장된 데이터는 파일 시스템의 저장 용량을 소모합니다.  하지만 FSx ONTAP 볼륨을 씬 프로비저닝하므로 볼륨은 저장되는 데이터 양에 해당하는 저장 용량만 차지합니다.



=== Cirrus Migrate Cloud MigrateOps 개념

CMC는 AWS Marketplace를 통해 제공되는 Cirrus Data Solutions, Inc.의 거래형 소프트웨어 즉 서비스(SaaS)입니다.  MigrateOps는 YAML에서 간단한 작업 구성을 사용하여 대규모 데이터 이동성 작업을 선언적으로 관리할 수 있는 CMC의 데이터 이동성 코드 자동화 기능입니다.  MigrateOps 구성은 데이터 이동성 작업을 실행하는 방법을 결정합니다.  MigrateOps에 대해 자세히 알아보려면 다음을 참조하세요.link:https://www.google.com/url?q=https://customer.cirrusdata.com/cdc/kb/articles/about-migrateops-hCCHcmhfbj&sa=D&source=docs&ust=1715480377722215&usg=AOvVaw033gzvuAlgxAWDT_kOYLg1["MigrateOps 소개"] .

MigrateOps는 전체 프로세스를 간소화하도록 특별히 구축된 자동화 우선 접근 방식을 취해 운영 중단 없이 클라우드 규모의 엔터프라이즈 데이터 이동성을 보장합니다.  CMC가 자동화를 위해 제공하는 이미 기능이 풍부한 기능 외에도 MigrateOps는 다음과 같이 외부에서 관리되는 다른 자동화를 추가로 추가합니다.

* OS 수정
* 애플리케이션 전환 및 승인 일정
* 다운타임 없는 클러스터 마이그레이션
* 퍼블릭/프라이빗 클라우드 플랫폼 통합
* 가상화 플랫폼 통합
* 엔터프라이즈 스토리지 관리 통합
* SAN(iSCSI) 구성


위의 작업이 완전히 자동화되면 온프레미스 소스 VM을 준비하는 모든 지루한 단계(AWS 에이전트 및 도구 추가, 대상 FSx LUN 생성, AWS 대상 인스턴스에서 iSCSI 및 Multipath/MPIO 설정, 애플리케이션 서비스를 중지/시작하는 모든 작업)가 YAML 파일에서 매개변수를 지정하기만 하면 제거됩니다.

FSx ONTAP 은 데이터 LUN을 제공하고 Amazon EC2 인스턴스 유형의 크기를 조정하는 데 사용되는 동시에 조직이 이전에 온프레미스 환경에서 사용하던 모든 기능을 제공합니다.  CMC의 MigrateOps 기능은 매핑된 iSCSI LUN 프로비저닝을 포함한 관련 단계 모두를 자동화하여 이를 예측 가능하고 선언적인 작업으로 전환하는 데 사용됩니다.

*참고*: CMC를 사용하려면 스토리지 소스 스토리지에서 FSx ONTAP 으로의 안전한 데이터 전송을 보장하기 위해 소스 및 대상 가상 머신 인스턴스에 매우 가벼운 에이전트를 설치해야 합니다.



== EC2 인스턴스와 함께 Amazon FSx ONTAP 사용하는 이점

Amazon EC2 인스턴스용 FSx ONTAP 스토리지는 다음과 같은 여러 가지 이점을 제공합니다.

* 가장 까다로운 작업 부하에도 일관된 고성능을 제공하는 높은 처리량과 낮은 대기 시간 스토리지
* 지능형 NVMe 캐싱으로 성능 향상
* 조정 가능한 용량, 처리량 및 IOP는 즉시 변경 가능하며 변화하는 스토리지 수요에 빠르게 적응할 수 있습니다.
* 온프레미스 ONTAP 스토리지에서 AWS로 블록 기반 데이터 복제
* 온프레미스 VMware 배포에 널리 사용되는 iSCSI를 포함한 다중 프로토콜 접근성
* NetApp Snapshot 기술과 SnapMirror 가 조율한 DR은 데이터 손실을 방지하고 복구 속도를 높입니다.
* 씬 프로비저닝, 데이터 중복 제거, 압축 및 압축을 포함하여 스토리지 공간과 비용을 줄이는 스토리지 효율성 기능
* 효율적인 복제를 통해 백업을 만드는 데 걸리는 시간을 몇 시간에서 단 몇 분으로 줄여 RTO를 최적화합니다.
* NetApp SnapCenter 사용한 파일 백업 및 복원을 위한 세부적인 옵션


FSx ONTAP iSCSI 기반 스토리지 계층으로 사용하여 Amazon EC2 인스턴스를 배포하면 고성능, 미션 크리티컬 데이터 관리 기능, 비용 절감형 스토리지 효율성 기능을 제공하여 AWS에서의 배포를 혁신할 수 있습니다.

플래시 캐시와 여러 iSCSI 세션을 실행하고 5%의 작업 세트 크기를 활용하면 FSx ONTAP ~350K의 IOPS를 제공하여 가장 집약적인 작업 부하도 충족할 수 있는 성능 수준을 제공합니다.

FSx ONTAP 에는 블록 스토리지 대역폭 제한이 아닌 네트워크 대역폭 제한만 적용되므로 사용자는 훨씬 더 큰 인스턴스 유형과 동일한 성능 속도를 달성하는 동시에 작은 Amazon EC2 인스턴스 유형을 활용할 수 있습니다.  이렇게 작은 인스턴스 유형을 사용하면 컴퓨팅 비용도 낮아져 TCO도 최적화됩니다.

FSx ONTAP 은 여러 프로토콜을 지원할 수 있는 기능도 장점으로, 다양한 기존 데이터 및 파일 서비스 요구 사항에 맞춰 단일 AWS 스토리지 서비스를 표준화하는 데 도움이 됩니다.  VMware vSphere에 많은 투자를 한 기업의 경우, 현재 시장 상황을 고려하면 AWS로 마이그레이션하는 것은 비용 효율적인 옵션이며, 독특한 기회를 제공합니다.
