---
sidebar: sidebar 
permalink: migration/shift-toolkit-supported-versions.html 
keywords: netapp, vmware, esxi, vm, migration, openshift, virtualization, hyper-v, proxmox, software, support, shift, toolkit 
summary: NetApp Shift Toolkit에서 Windows 및 Linux 게스트 운영 체제, ONTAP 버전, 하이퍼바이저가 지원되는지 확인하세요. 
---
= NetApp Shift Toolkit에 지원되는 버전
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Shift Toolkit에서 Windows 및 Linux 게스트 운영 체제, ONTAP 버전, 하이퍼바이저가 지원되는지 확인하세요.



== 지원되는 VM 게스트 운영 체제

Shift Toolkit은 VM 변환을 위해 다음과 같은 Windows 및 Linux 게스트 운영 체제를 지원합니다.

.윈도우 운영 체제
* 윈도우 10
* 윈도우 11
* 윈도우 서버 2016
* 윈도우 서버 2019
* 윈도우 서버 2022
* 윈도우 서버 2025


.리눅스 운영체제
* 센트OS 리눅스 7.x
* 알마 리눅스 7.x
* Red Hat Enterprise Linux 7.2 이상
* 레드햇 엔터프라이즈 리눅스 8.x
* 레드햇 엔터프라이즈 리눅스 9.x
* 우분투 2018
* 우분투 2022
* 우분투 2024
* 데비안 12
* 수세 리눅스 엔터프라이즈 서버 12
* 수세 리눅스 엔터프라이즈 서버 15



NOTE: CentOS Linux와 Red Hat Enterprise Linux 버전 5, 6은 지원되지 않습니다.


NOTE: Windows Server 2008은 공식적으로 지원되지 않습니다. 하지만 변환 프로세스가 작동할 수도 있으며 일부 고객은 Windows Server 2008 VM을 성공적으로 변환했습니다. 마이그레이션 후에는 IP 주소를 수동으로 업데이트해야 합니다. IP 할당 자동화에 사용되는 PowerShell 버전은 Windows Server 2008과 호환되지 않습니다.



== 지원되는 ONTAP 버전

Shift Toolkit은 ONTAP 9.14.1 이상을 지원합니다.



== 지원되는 하이퍼바이저

Shift Toolkit은 VM 마이그레이션 및 변환을 위해 다음과 같은 하이퍼바이저 플랫폼을 지원합니다.


NOTE: 현재 릴리스에서는 Hyper-V, VMware, OpenShift, Oracle Virtualization을 통해서만 엔드투엔드 가상 머신 마이그레이션이 지원됩니다. KVM 대상의 경우 디스크 변환만 지원됩니다.

.VMware vSphere
Shift 툴킷은 vSphere 7.0.3 이상에서 검증되었습니다.

.마이크로소프트 하이퍼-V
Shift 툴킷은 다음 Hyper-V 역할에 대해 검증되었습니다.

* Windows Server 2019에서 실행되는 Hyper-V 역할
* Windows Server 2022에서 실행되는 Hyper-V 역할
* Windows Server 2025에서 실행되는 Hyper-V 역할


.레드햇 오픈시프트
Shift 툴킷은 4.17 이상에서 실행되는 Red Hat OpenShift 및 OpenShift Virtualization에 대해 검증되었습니다.

.Oracle Linux 가상화 관리자
Shift 툴킷은 다음 Oracle Linux Virtualization Manager 버전에 대해 검증되었습니다.

* Oracle Linux Virtualization Manager 4.5 이상
* Oracle Linux Virtualization Manager 호스트에는 ovirt-engine-4.5.4-1.el8 RPM 이상이 설치되어 있어야 합니다.


.케이비엠
KVM 대상의 경우 Shift Toolkit은 디스크 형식 변환(VMDK에서 QCOW2 또는 RAW로)만 지원합니다. 대상 드롭다운에서 KVM을 선택하는 경우 하이퍼바이저 연결 세부 정보는 필요하지 않습니다. 변환 후 QCOW2 디스크를 사용하여 KVM 기반 플랫폼에서 VM을 프로비저닝합니다.
