---
sidebar: sidebar 
permalink: proxmox/proxmox-ontap.html 
keywords: netapp, proxmox, proxmox ve, all-flash, nfs, iscsi, ontap, storage, aff 
summary: 'NAS 프로토콜(NFS, SMB) 및 SAN 프로토콜(FC, iSCSI, NVMe)을 사용하여 Proxmox 가상 환경(VE)용 ONTAP 스토리지를 프로비저닝합니다. Proxmox VE 클러스터의 공유 스토리지를 구성하려면 프로토콜별 적절한 절차를 선택하십시오.' 
---
= NetApp ONTAP 사용한 Proxmox VE용 스토리지 프로토콜에 대해 알아보세요.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NAS 프로토콜(NFS, SMB) 및 SAN 프로토콜(FC, iSCSI, NVMe)을 사용하여 Proxmox 가상 환경(VE)용 ONTAP 스토리지를 프로비저닝합니다. Proxmox VE 클러스터의 공유 스토리지를 구성하려면 프로토콜별 적절한 절차를 선택하십시오.

Proxmox VE 호스트가 FC, 이더넷 또는 기타 지원되는 인터페이스를 ONTAP 논리 인터페이스와 통신할 수 있는 스위치에 케이블로 연결했는지 확인하십시오. 항상 확인하세요 https://mysupport.netapp.com/matrix/#welcome["상호 운용성 매트릭스 도구"] 지원되는 구성의 경우. 예시 시나리오는 각 Proxmox VE 호스트에 두 개의 고속 네트워크 인터페이스 카드가 있고, 이 카드들이 서로 연결되어 내결함성과 성능 향상을 위한 본딩 인터페이스를 구성한다는 가정하에 작성되었습니다. 호스트 관리, VM/컨테이너 트래픽, 스토리지 액세스를 포함한 모든 네트워크 트래픽에 동일한 업링크 연결이 사용됩니다. 사용 가능한 네트워크 인터페이스가 더 많을 경우, 스토리지 트래픽을 다른 유형의 트래픽과 분리하는 것을 고려하십시오.

ONTAP 스토리지 아키텍처 및 지원되는 스토리지 유형에 대한 자세한 내용은 다음을 참조하십시오. link:proxmox-ontap-architecture.html["Proxmox VE용 ONTAP 스토리지 아키텍처에 대해 알아보세요."] 그리고 link:proxmox-storage-types.html["Proxmox VE에서 지원하는 스토리지 유형에 대해 알아보세요."].


NOTE: LVM을 SAN 프로토콜(FC, iSCSI, NVMe-oF)과 함께 사용할 경우, 볼륨 그룹에는 여러 개의 LUN 또는 NVMe 네임스페이스가 포함될 수 있습니다. 이 경우 데이터 무결성을 보장하기 위해 모든 LUN 또는 네임스페이스는 동일한 일관성 그룹에 속해야 합니다. 저희는 여러 ONTAP SVM에 걸쳐 있는 볼륨 그룹을 지원하지 않습니다. 각 볼륨 그룹은 동일한 SVM의 LUN 또는 네임스페이스로 생성되어야 합니다.



== 저장 프로토콜을 선택하세요

사용 환경 및 요구 사항에 맞는 프로토콜을 선택하십시오.

* link:proxmox-ontap-smb.html["SMB/CIFS 스토리지 구성"] - 다중 네트워크 연결을 통해 내결함성과 향상된 성능을 제공하기 위해 다중 채널 지원 기능을 갖춘 Proxmox VE용 SMB/CIFS 파일 공유를 구성합니다.
* link:proxmox-ontap-nfs.html["NFS 스토리지 구성"] - nConnect 또는 세션 트렁킹을 사용하여 Proxmox VE용 NFS 스토리지를 구성하여 다중 네트워크 연결을 통해 내결함성과 성능 향상을 구현합니다.
* link:proxmox-ontap-fc.html["FC를 사용하여 LVM을 구성합니다."] - Proxmox VE 호스트 간 고성능 및 저지연 블록 스토리지 액세스를 위해 파이버 채널을 사용하여 LVM(논리 볼륨 관리자)을 구성합니다.
* link:proxmox-ontap-iscsi.html["iSCSI를 사용하여 LVM 구성"] - 표준 이더넷 네트워크를 통해 멀티패스를 지원하는 블록 스토리지 액세스를 위해 iSCSI를 사용하여 LVM(논리 볼륨 관리자)을 구성합니다.
* link:proxmox-ontap-nvme-fc.html["NVMe/FC를 사용하여 LVM 구성"] - 최신 NVMe 프로토콜을 사용하여 고성능 블록 스토리지를 구현하기 위해 파이버 채널을 통한 NVMe로 논리 볼륨 관리자(LVM)를 구성합니다.
* link:proxmox-ontap-nvme-tcp.html["NVMe/TCP를 사용하여 LVM 구성"] - 최신 NVMe 프로토콜을 사용하여 표준 이더넷 네트워크를 통해 고성능 블록 스토리지를 구현하기 위해 NVMe over TCP를 사용하는 논리 볼륨 관리자(LVM)를 구성합니다.

