---
sidebar: sidebar 
permalink: proxmox/proxmox-deploy-guidelines.html 
keywords: netapp, proxmox, proxmox ve, all-flash, nfs, iscsi, nvme, fc, ontap, storage, aff, asa, virtual machines, vm, containers, proxmox backup server 
summary: 'Proxmox Virtual Environment(VE)는 NetApp ONTAP 스토리지와 통합되어 가상 머신 및 컨테이너를 위한 공유 스토리지를 제공하므로 더욱 빠른 라이브 마이그레이션, 일관된 템플릿 및 중앙 집중식 백업이 가능합니다. ONTAP 스토리지 시스템을 사용하여 Proxmox VE 클러스터를 배포하고 최적화하기 위한 아키텍처, 네트워크 및 스토리지 구성, 그리고 모범 사례에 대해 알아보세요.' 
---
= NetApp ONTAP 스토리지를 사용하는 Proxmox 가상 환경 배포 지침
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Proxmox Virtual Environment(VE)는 NetApp ONTAP 스토리지와 통합되어 가상 머신 및 컨테이너를 위한 공유 스토리지를 제공하므로 더욱 빠른 라이브 마이그레이션, 일관된 템플릿 및 중앙 집중식 백업이 가능합니다. ONTAP 스토리지 시스템을 사용하여 Proxmox VE 클러스터를 배포하고 최적화하기 위한 네트워크 및 스토리지 구성 지침과 모범 사례에 대해 알아보세요.

지원되는 스토리지 유형 및 콘텐츠 호환성에 대한 자세한 내용은 다음을 참조하세요. link:proxmox-storage-types.html["Proxmox VE에서 지원하는 스토리지 유형에 대해 알아보세요."].



== 네트워크 구성 지침

네트워크 성능과 안정성을 최적화하려면 다음 지침을 따르십시오.

* Proxmox VE 노드와 ONTAP 스토리지 간에 이중화된 네트워크 경로를 확보하십시오.
* 대역폭 및 내결함성 향상을 위해 링크 집합(LACP)을 사용하십시오.
* 스패닝 트리 문제를 방지하도록 네트워크 토폴로지를 설계하십시오. 필요한 경우 RSTP 또는 MSTP와 같은 기능을 사용하십시오.
* VLAN을 구현하여 다양한 유형의 트래픽을 분리하고 보안을 강화하십시오.
* 스토리지 트래픽 성능 향상을 위해 모든 네트워크 장치에 점보 프레임(MTU 9000)을 구성하십시오.
* VLAN 영역을 구성할 때 Linux Bridge를 통한 Open vSwitch(OVS) 사용을 고려하십시오.




== 스토리지 구성 모범 사례

스토리지 성능 및 확장성을 최적화하려면 다음 모범 사례를 따르십시오.

* ONTAP의 스냅샷 및 클론 생성과 같은 고급 데이터 관리 기능을 활용하여 데이터 보호 및 복구를 강화하십시오.
* 대용량 요구 사항에는 FlexGroup 볼륨을 사용하여 ONTAP 확장성의 잠재력을 최대한 활용하십시오.
* 지리적으로 분산된 환경에서는 FlexCache 사용하여 이미지와 템플릿을 Proxmox VE 노드에 더 가깝게 배포함으로써 배포 시간을 단축하고 중앙에서 관리할 수 있습니다.
* FlexGroup NFS와 함께 사용할 때는 nConnect 또는 세션 트렁킹과 pNFS를 조합하여 성능과 가용성을 최적화하십시오.
* 블록 프로토콜의 경우, 승인된 Proxmox VE 노드만 접근할 수 있도록 적절한 영역 설정 및 LUN 마스킹을 적용해야 합니다.
* 가상 머신의 성장과 데이터 요구 사항을 수용할 수 있도록 충분한 저장 용량을 할당하십시오.
* 스토리지 계층화를 구현하여 성능과 비용 효율성을 최적화하십시오.
* NetApp 관리 도구를 사용하여 스토리지 성능 및 상태를 정기적으로 모니터링하십시오.
* NetApp Console 사용하여 여러 ONTAP 시스템을 중앙에서 관리하십시오.
* ONTAP 에서 랜섬웨어 공격으로부터 보호하기 위해 랜섬웨어 방지 기능을 활성화하십시오.




== Proxmox VE 구성 지침

NetApp ONTAP 스토리지를 사용하여 Proxmox VE를 최적화하려면 다음 지침을 따르십시오.

* 최신 기능 및 버그 수정 사항을 활용하려면 Proxmox VE를 최신 안정 버전으로 업데이트하십시오.
* Proxmox VE를 구성하여 VM 스토리지로 NetApp ONTAP 의 공유 스토리지를 사용하도록 설정합니다.
* Proxmox VE 클러스터를 설정하여 고가용성과 VM의 실시간 마이그레이션을 지원합니다.
* 클러스터 통신에는 이중화된 네트워크를 사용하고, 라이브 마이그레이션을 위해서는 별도의 네트워크를 사용하십시오.
* 충돌을 방지하기 위해 클러스터 간에 동일한 VM 또는 컨테이너 ID를 재사용하지 마십시오.
* 가상 머신에서 더 나은 성능과 기능을 얻으려면 VirtIO SCSI 단일 컨트롤러를 사용하십시오.
* I/O 요구량이 높은 가상 머신의 경우 I/O 스레드 옵션을 활성화하십시오.
* VM 디스크에서 폐기/TRIM 지원을 활성화하여 스토리지 사용량을 최적화하십시오.

