---
sidebar: sidebar 
permalink: euc/euc-overview.html 
keywords: euc, digital workspace, virtual desktop, vdi, virtual desktop infrastructure, cloud desktop, virtual application, application virtualization, app virtualization, virtual desktop management, desktop management, application management 
summary:  
---
= NetApp을 통한 최종 사용자 컴퓨팅에 대해 알아보십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
최종 사용자 컴퓨팅(EUC)은 사용자가 언제 어디서든 어떤 장치에서든 데스크톱과 애플리케이션에 액세스할 수 있도록 하는 기술입니다. NetApp을 사용하는 EUC 솔루션에는 가상 데스크톱 인프라(VDI), 애플리케이션 가상화 및 사용자 프로필 관리가 포함됩니다. NetApp의 EUC 솔루션을 통해 기업은 생산성을 향상시키고 비용을 절감하며 최종 사용자의 보안을 강화할 수 있습니다.



[[what-is-end-user-computing-euc]]
== 최종 사용자 컴퓨팅(EUC)이란 무엇인가요?

최종 사용자 컴퓨팅(EUC)은 사용자가 언제 어디서든 어떤 기기에서든 데스크톱과 애플리케이션에 접근할 수 있도록 해주는 기술입니다. EUC 솔루션은 일반적으로 가상 데스크톱 인프라(VDI), 애플리케이션 가상화, 사용자 프로필 관리 도구 등을 포함합니다. EUC를 통해 조직은 생산성을 향상시키고 비용을 절감하며 최종 사용자의 보안을 강화할 수 있습니다. 파일 공유와 홈 디렉터리 또한 EUC 솔루션의 일부로, 사용자가 어떤 기기에서든 파일과 데이터에 접근할 수 있도록 지원합니다.

사용자는 단일 애플리케이션 또는 전체 데스크톱을 통해 업무를 수행하기 위해 애플리케이션에 액세스해야 합니다. 일부 사용자는 데스크톱 워크플로 또는 특정 애플리케이션 사용 사례를 위해 고성능 그래픽 애플리케이션이 필요할 수 있습니다. NetApp을 사용하는 EUC 솔루션은 사용자의 요구 사항에 따라 각 사용자에게 적합한 솔루션을 제공할 수 있습니다. NetApp의 EUC 솔루션을 통해 조직은 사용자가 언제 어디서든 어떤 장치에서든 데스크톱 및 애플리케이션에 액세스할 수 있도록 지원하는 동시에 데이터를 안전하고 효율적으로 저장할 수 있습니다.

조직은 온프레미스, 클라우드 또는 하이브리드 환경에 EUC 솔루션을 배포할 수 있으므로 필요에 가장 적합한 배포 모델을 유연하게 선택할 수 있습니다. NetApp의 EUC 솔루션을 통해 조직은 생산성을 향상시키고 비용을 절감하며 최종 사용자의 보안을 강화하는 동시에 어디서든 작업할 수 있는 유연성을 제공할 수 있습니다.



[[high-level-benefits-of-end-user-computing-with-netapp]]
== NetApp을 사용한 최종 사용자 컴퓨팅의 주요 이점

NetApp의 EUC 솔루션은 조직에 다음과 같은 여러 이점을 제공합니다. * 생산성 향상: EUC를 통해 사용자는 언제 어디서든 어떤 장치에서든 데스크톱과 애플리케이션에 액세스할 수 있으므로 생산성과 협업이 향상됩니다. * 비용 절감: EUC는 데스크톱 및 애플리케이션 관리를 중앙 집중화하여 고가의 하드웨어 및 소프트웨어에 대한 필요성을 줄임으로써 조직의 비용을 절감하는 데 도움이 됩니다. * 보안 강화: EUC는 데스크톱 및 애플리케이션 관리를 중앙 집중화하여 데이터 유출 및 기타 보안 사고의 위험을 줄임으로써 조직의 보안을 강화하는 데 도움이 됩니다. * 확장성: NetApp의 EUC 솔루션은 확장 가능하도록 설계되어 조직이 필요에 따라 사용자를 쉽게 추가하거나 제거할 수 있습니다. * 유연성: NetApp의 EUC 솔루션은 온프레미스, 클라우드 또는 하이브리드 환경에 배포할 수 있으므로 조직은 요구 사항에 가장 적합한 배포 모델을 유연하게 선택할 수 있습니다.

자세한 내용은 link:euc-benefits.html["최종 사용자 컴퓨팅을 위한 NetApp 스토리지의 이점"] 페이지를 참조하십시오.



[[netapps-euc-solutions]]
== NetApp의 EUC 솔루션

NetApp은 다음과 같은 다양한 EUC 솔루션을 제공합니다. * 가상 데스크톱 인프라(VDI): VDI 솔루션을 통해 조직은 최종 사용자에게 가상 데스크톱을 제공하여 모든 장치에서 언제 어디서든 데스크톱과 애플리케이션에 액세스할 수 있도록 지원합니다. * 애플리케이션 가상화: 애플리케이션 가상화 솔루션을 통해 조직은 최종 사용자에게 가상 애플리케이션을 제공하여 모든 장치에서 언제 어디서든 애플리케이션에 액세스할 수 있도록 지원합니다. * 파일 공유 및 홈 디렉터리: 파일 공유 및 홈 디렉터리 솔루션을 통해 조직은 사용자가 모든 장치에서 언제 어디서든 파일과 데이터에 액세스할 수 있도록 지원하는 동시에 데이터를 안전하고 효율적으로 저장할 수 있도록 지원합니다. * 사용자 프로필 관리: 사용자 프로필 관리 솔루션을 통해 조직은 여러 장치에서 사용자 프로필과 설정을 관리하여 사용자가 사용하는 장치에 관계없이 일관된 환경을 제공할 수 있습니다.
