---
sidebar: sidebar 
permalink: vmware/vmw-sovereign-cloud.html 
keywords: NetApp Solutions, vmware, sovereign cloud 
summary:  
---
= VMware Sovereign Cloud에 대해 알아보세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware Sovereign Cloud는 민감한 데이터를 처리하는 조직의 데이터 주권, 관할권 통제 및 규정 준수를 우선시하는 클라우드 컴퓨팅을 위한 프레임워크입니다.  이러한 접근 방식은 최신 클라우드 인프라의 유연성과 기능을 제공하는 동시에 데이터가 수집된 국가의 독점적인 통제와 권한 하에 유지되도록 보장합니다.

주권이라는 개념은 국가 및 주 정부와 금융, 의료와 같이 규제가 엄격한 산업 등 매우 민감한 데이터를 처리하고 유지 관리하는 많은 기관의 클라우드 컴퓨팅에 필수적인 구성 요소로 떠오르고 있습니다.  국가 정부 역시 디지털 경제 역량을 확대하고 클라우드 서비스에 대한 다국적 기업 의존도를 낮추는 방안을 모색하고 있습니다.



== VMware Sovereign Cloud Initiative

VMware에서는 주권 클라우드를 다음과 같은 것으로 정의합니다.

* 민간 및 공공 부문 조직 모두의 중요 데이터(예: 국가 데이터, 기업 데이터, 개인 데이터)의 가치를 보호하고 활용합니다.
* 디지털 경제를 위한 국가적 역량을 제공합니다
* 감사된 보안 제어로 데이터를 보호합니다.
* 데이터 개인정보 보호법 준수를 보장합니다
* 전체 관할권 제어를 통해 데이터 상주권과 데이터 주권을 모두 제공하여 데이터 제어를 개선합니다.




== 신뢰할 수 있는 VMware Sovereign 클라우드 서비스 공급업체와의 파트너십

성공을 보장하려면 조직은 신뢰할 수 있고 정통하고 자율적인 주권형 클라우드 플랫폼을 호스팅할 수 있는 파트너와 협력해야 합니다.  VMware Sovereign Cloud 이니셔티브에서 인정받은 VMware 클라우드 공급업체는 VMware Sovereign Cloud 프레임워크에 명시된 주요 원칙과 모범 사례를 구현하는 최신 소프트웨어 정의 아키텍처를 기반으로 클라우드 솔루션을 설계하고 운영하는 데 전념합니다.

* *데이터 주권 및 관할권 통제* – 모든 데이터는 해당 데이터가 수집된 국가에 상주하며 해당 국가의 독점적 통제 및 권한의 적용을 받습니다.  운영은 관할권 내에서 완전히 관리됩니다.
* *데이터 접근 및 무결성* – 클라우드 인프라는 복원력이 뛰어나고 관할 구역 내 최소 2개의 데이터 센터에서 사용 가능하며 안전하고 개인적인 연결 옵션이 제공됩니다.
* *데이터 보안 및 규정 준수* – 정보 보안 관리 시스템 통제는 업계에서 인정하는 글로벌(또는 지역) 표준에 따라 인증을 받았으며 정기적으로 감사를 받습니다.
* *데이터 독립성 및 이동성* – 공급업체 클라우드 잠금을 방지하고 애플리케이션 이식성 및 독립성을 활성화하기 위한 최신 애플리케이션 아키텍처 지원


VMware에 대한 자세한 내용은 다음에서 확인하세요.

* link:https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/docs/vmw-sovereign-cloud-solution-brief-customer.pdf["VMware Sovereign Cloud 개요"]
* link:https://www.vmware.com/topics/glossary/content/sovereign-cloud.html["VMware Sovereign Cloud란 무엇인가요?"]
* link:https://blogs.vmware.com/cloud/2021/10/06/vmware-sovereign-cloud/["새로운 VMware Sovereign Cloud 이니셔티브 소개"]
* link:https://www.vmware.com/solutions/cloud-infrastructure/sovereign-cloud["VMware Sovereign 클라우드 솔루션"]

