---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-automation.html 
keywords:  
summary:  
---
= 관리를 위해 ONTAP 및 VMware API를 사용하는 방법에 대해 알아보세요.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 과 VMware는 스토리지와 가상화 플랫폼 간의 원활한 통합과 자동화를 위한 API를 제공합니다.  이를 통해 간소화된 프로비저닝, 모니터링 및 데이터 보호가 가능해져 워크플로 일관성이 향상됩니다.



== 소개

VMware는 관리자가 다양한 VMware 제품 및 서비스와 프로그래밍 방식으로 상호 작용할 수 있도록 하는 다양한 API를 제공하여 운영의 효율성과 일관성을 향상시킵니다.  또한 NetApp ONTAP API는 관리자가 특히 VMware 워크로드와 함께 스토리지 환경 관리를 자동화, 통합 및 최적화할 수 있는 강력한 도구 세트를 제공합니다.  이러한 API는 ONTAP 스토리지 시스템과 VMware 간의 원활한 상호작용을 촉진하여 효율성, 성능, 데이터 보호를 향상시킵니다.



== VMware 기반 API

* *VMware vSphere API:* vSphere API는 관리자가 VMware vSphere 환경을 관리하고 자동화할 수 있도록 해주는 포괄적인 API입니다.  가상 머신 프로비저닝, 구성, 모니터링, 수명 주기 관리를 포함한 광범위한 vSphere 기능에 대한 액세스를 제공합니다.
* *VMware vCenter Server REST API:* vCenter Server REST API는 vCenter Server와 관련 구성 요소를 관리하기 위한 최신 RESTful 인터페이스를 제공합니다.  다른 시스템 및 도구와의 자동화 및 통합이 간소화됩니다.
* *VMware Cloud Foundation API:* VMware 소프트웨어 정의 데이터 센터(SDDC) API는 VMware SDDC 환경 내의 다양한 구성 요소와 서비스에 대한 프로그래밍 방식 액세스를 제공합니다.  이러한 API를 사용하면 관리자와 개발자가 컴퓨팅, 스토리지, 네트워킹, 관리 서비스 등 데이터 센터의 다양한 측면을 자동화, 관리 및 통합할 수 있습니다.
* *VMware vSphere 스토리지 API - 스토리지 인식:* VASA는 관리 및 운영을 위해 스토리지 어레이와 vCenter를 통합하는 API 세트입니다.  이 아키텍처는 VMware vSphere와 스토리지 시스템 간의 통신을 처리하는 VASA Provider를 포함한 여러 구성 요소를 기반으로 합니다.  ONTAP 사용하면 공급자가 ONTAP tools for VMware vSphere 의 일부로 구현됩니다.
* *VMware vSphere 스토리지 API - 어레이 통합:* VAAI는 VMware vSphere ESXi 호스트와 스토리지 장치 간의 통신을 가능하게 하는 API 세트입니다.  API에는 호스트가 스토리지 작업을 어레이로 오프로드하는 데 사용되는 일련의 기본 작업이 포함되어 있습니다.  VAAI는 저장 용량이 많은 작업에 대해 상당한 성능 향상을 제공할 수 있습니다.




== ONTAP 기반 API

* * NetApp ONTAP REST API:* ONTAP REST API는 ONTAP 스토리지 시스템을 관리하기 위한 최신 RESTful 인터페이스를 제공합니다.  프로비저닝, 모니터링, 구성 등의 스토리지 작업 자동화를 간소화합니다.  VMware vSphere 및 기타 VMware 관리 도구와 쉽게 통합할 수 있어 VMware 환경에서 직접 자동화된 스토리지 작업이 가능합니다.  기본 스토리지 관리부터 고급 데이터 보호 및 복제 작업까지 광범위한 작업을 지원하므로 확장 가능하고 유연한 스토리지 관리가 가능합니다.
* * VMware vSphere용 ONTAP 도구:* ONTAP tools for VMware vSphere ONTAP 과 vSphere를 통합하기 위한 도구 세트입니다.  VASA API 프레임워크의 공급자 기능을 구현합니다.  ONTAP 도구에는 vCenter 플러그인, VMware Site Recovery Manager용 스토리지 복제 어댑터(SRA), 자동화 애플리케이션을 구축하는 데 사용할 수 있는 REST API 서버도 포함되어 있습니다.




== 요약

요약하자면, ONTAP API를 사용하면 관리자는 VMware 환경에서 데이터스토어를 생성하고 구성하는 스크립트를 작성하여 빠르고 일관된 스토리지 프로비저닝을 보장할 수 있습니다.  또한 VMware 가상 머신의 스냅샷 생성, 일정 예약, 삭제를 자동화하여 효율적인 데이터 보호 및 복구 옵션을 제공할 수 있습니다.  SnapMirror API는 복제 관계 설정 및 관리의 자동화를 촉진하여 VMware 워크로드에 대한 강력한 재해 복구 솔루션을 보장합니다.  관리자는 스크립트를 구현하여 스토리지 성능 측정 항목을 모니터링하고 성능 임계값을 초과하면 알림이나 자동화된 작업을 트리거하여 VMware 워크로드에 대한 최적의 스토리지 성능을 보장할 수도 있습니다.  ONTAP API를 vSphere 및 vRealize에서 제공하는 것과 같은 VMware API와 통합함으로써 관리자는 원활하고 고도로 자동화된 관리 환경을 구현하여 가상화된 인프라의 전반적인 효율성과 안정성을 향상시킬 수 있습니다.
