---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-nfs-requirements.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, array, ontap tools, otv, sddc, sddc manager, ontap tools, ontap tools 10 
summary: vSphere 클러스터와 NetApp ONTAP NFS 데이터스토어를 VMware Cloud Foundation 관리 도메인으로 통합하기 위한 요구 사항을 검토하십시오. 
---
= NFS 데이터스토어를 사용하여 vCenter 서버 인스턴스를 VCF 관리 도메인으로 통합하기 위한 배포 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
vSphere 클러스터와 NetApp ONTAP NFS 데이터스토어를 VMware Cloud Foundation 관리 도메인으로 통합하기 위한 요구 사항을 검토하십시오.

컨버전스 프로세스에는 AFF 또는 AFX 스토리지 시스템, NFS 트래픽용 SVM 및 LIF, 스위치의 NFS VLAN, vSphere 호스트가 있는 vSphere 클러스터 및 vCenter, 그리고 vMotion을 위한 전용 네트워크 세그먼트가 필요합니다.



[[infrastructure-requirements]]
== 인프라 요구 사항

다음 구성 요소와 구성이 제대로 되어 있는지 확인하세요.

* NetApp NFS 트래픽을 허용하도록 구성된 스토리지 가상 머신(SVM)이 있는 AFF 또는 AFX 스토리지 시스템.
* NFS 트래픽을 전송하고 SVM과 연결하기 위해 IP 네트워크에서 생성된 논리 인터페이스(LIF)입니다.
* 최소 2개의 vSphere 호스트와 클러스터에 공동 배치된 vCenter 어플라이언스가 포함된 vSphere 클러스터.
* 이 목적으로 설정된 VLAN 또는 네트워크 세그먼트에서 vMotion 및 NFS 스토리지 트래픽을 위해 구성된 분산 포트 그룹입니다.
* vCenter를 VCF 관리 도메인으로 통합하기 위한 VCF Installer 툴입니다.
* ONTAP 도구의 전제 조건.
+
ONTAP 도구의 전제 조건에 대한 전체 정보는 다음을 참조하세요. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/prerequisites.html#system-requirements["ONTAP tools for VMware vSphere 의 필수 구성 요소"] .

+
ONTAP tools for VMware vSphere HA 또는 비 HA 구성으로 설치할 수 있습니다.





[[additional-resources]]
== 추가 자료

* vSphere를 VCF로 통합할 때 지원되는 스토리지 및 기타 고려 사항에 대해서는 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/deployment/converging-your-existing-vsphere-infrastructure-to-a-vcf-or-vvf-platform-/supported-and-not-supported-configurations.html["VCF로 수렴하기 위한 지원 및 미지원 구성"]을 참조하십시오.
* ONTAP 스토리지 시스템 구성에 대한 정보는 다음을 참조하십시오.link:https://docs.netapp.com/us-en/ontap["ONTAP 9 문서"] .
* VCF 구성에 대한 자세한 내용은 link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation 9.1 설명서"]을 참조하십시오.




[[whats-next]]
== 다음은 무엇인가요?

배포 요구 사항을 검토한 후link:vmw-vcf-mgmt-nfs-deploy.html["ONTAP 도구 배포 및 NFS 데이터 저장소 프로비저닝"] .
