---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-security.html 
keywords:  
summary:  
---
= VMware 워크로드에 대한 보안 및 랜섬웨어 위험 완화에 대해 알아보세요.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 암호화, 스냅샷, 고급 액세스 제어를 통해 VMware 환경에서 보안과 랜섬웨어 보호를 강화하고, VMware의 보안 기능을 보완하여 데이터를 보호합니다.



== 소개

VMware 환경에서 NetApp ONTAP 의 고급 기능을 활용하면 조직은 데이터의 무결성, 가용성 및 보안을 보장할 수 있습니다.

이러한 기술이 어떻게 함께 작동하여 *보안*과 *백업 이점*을 제공하는지 자세히 살펴보겠습니다.



== 보안 및 랜섬웨어

가상화된 환경에서 보안은 가장 중요한 문제이며, NetApp ONTAP VMware 인프라 내에서 보안을 강화하는 강력한 기능을 제공합니다.  ONTAP 저장 중인 데이터와 전송 중인 데이터에 대한 암호화를 제공하여 민감한 정보가 무단 액세스로부터 보호되도록 보장합니다.  암호화 키는 안전하게 관리되며 ONTAP 소프트웨어 기반 및 하드웨어 기반 암호화 솔루션을 모두 지원합니다.  ONTAP vSphere의 기본 보안 기능 및 타사 보안 솔루션과 같은 VMware의 보안 도구와 통합되어 안전하고 규정을 준수하는 환경을 조성하는 데 도움이 됩니다.



== 랜섬웨어 방어

랜섬웨어 공격은 조직에 심각한 위협이 되며, VMware와 ONTAP 결합하면 강력한 방어 메커니즘을 제공할 수 있습니다.  ONTAP의 스냅샷 기술을 사용하면 랜섬웨어에 의해 변경되거나 삭제될 수 없는 변경 불가능한 스냅샷을 생성할 수 있습니다.  공격이 발생하면 이러한 스냅샷을 사용하여 영향을 받은 VM과 데이터 저장소를 공격 이전 상태로 신속하게 복원하여 가동 중지 시간과 데이터 손실을 최소화할 수 있습니다.  또한 ONTAP은 보안 정보 및 이벤트 관리(SIEM) 시스템과 통합되어 의심스러운 활동을 사전에 모니터링하고 경고할 수 있습니다.  ONTAP 또한 보안을 더욱 강화하기 위해 다중 인증(MFA)과 역할 기반 액세스 제어(RBAC)를 지원합니다.



== 랜섬웨어 복구 보증

NetApp 랜섬웨어 보증은 조직에 랜섬웨어 공격으로부터 보호하기 위한 강력하고 안정적인 솔루션을 제공합니다.  NetApp ONTAP 의 고급 기능을 활용하면 조직은 데이터의 보안과 가용성을 보장할 수 있습니다.  이 보증은 랜섬웨어 공격이 발생할 경우 데이터를 신속하고 효과적으로 복구하여 가동 중지, 데이터 손실 및 재정적 영향을 최소화할 수 있다는 안도감을 제공합니다.  데이터 보안과 복원력에 대한 이러한 노력 덕분에 NetApp 진화하는 사이버 위협으로부터 중요 자산을 보호하고자 하는 조직에게 이상적인 파트너가 되었습니다.



== 고급 보안 기능

ONTAP 다중 테넌트 환경에서 데이터와 리소스를 격리하는 보안 다중 테넌시, 민감한 데이터에 대한 액세스를 추적하고 기록하는 규정 준수 감사와 같은 고급 보안 기능이 포함되어 있습니다.  이러한 기능을 통해 데이터가 안전하게 보호되고 조직이 업계 규정 및 표준을 준수함을 입증할 수 있습니다.



== 요약

ONTAP의 보안 기능(암호화, 변경 불가능한 스냅샷, 고급 액세스 제어 등)과 VMware 도구를 통합하면 랜섬웨어를 포함한 사이버 위협에 대한 강력한 방어 기능을 제공합니다.  ONTAP은 안전한 멀티 테넌시와 규정 준수 감사를 지원하여 데이터 보호와 규정 준수를 보장합니다.

NetApp ONTAP 과 VMware는 가상화된 환경을 보호하기 위한 포괄적인 솔루션을 제공하여 조직이 데이터를 보호하고, 가동 중지 시간을 최소화하고, 비즈니스 연속성을 유지할 수 있도록 지원합니다.  이러한 기술을 구현하면 기업이 현대 IT 과제를 해결하고 중요한 자산을 진화하는 보안 위협으로부터 보호하는 데 도움이 됩니다.
