---
sidebar: sidebar 
permalink: vmware/vmw-vvol-nfs-migration-best-practices.html 
keywords: netapp, vmware, nfs, ontap, deployment, best practices, connectivity, provisioning, nconnect, security 
summary: 연결, 프로비저닝, nConnect 및 보안 등 ONTAP을 사용하는 VMware 환경에서 NFS 데이터스토어를 사용하기 위한 모범 사례에 대해 알아보십시오. 
---
= ONTAP을 사용하는 VMware 환경에서 NFS 데이터스토어 사용을 위한 모범 사례
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
vVols에서 마이그레이션한 후 최적의 성능과 안정성을 보장하기 위해 연결성, 프로비저닝, nConnect 및 보안 등 ONTAP를 사용하는 VMware 환경에서 NFS 데이터스토어 사용에 대한 모범 사례를 알아보십시오.



[[deployment-best-practices]]
== 배포 모범 사례

ONTAP을 사용하여 VMware 환경에 NFS 데이터스토어를 구축할 때 다음과 같은 모범 사례를 고려하십시오:

* 환경 요구 사항에 따라 NFSv3 또는 NFSv4.1을 사용하십시오. NFSv3은 널리 지원됩니다. NFSv4.1은 Kerberos 인증 및 멀티패싱을 위한 세션 트렁킹을 추가합니다. 세션 트렁킹에는 ONTAP 9.14.1 이상이 필요합니다.
* 스토리지 트래픽을 격리하고 성능을 향상시키려면 NFS 트래픽용 전용 네트워크 인터페이스를 구성하십시오.
* SVM에서 vStorage 옵션을 활성화하십시오. VMware VAAI용 NetApp NFS 플러그인에 이 옵션이 필요합니다.
* ESXi 호스트, 네트워크 스위치 및 ONTAP에서 엔드 투 엔드로 점보 프레임(MTU 9000)을 활성화합니다.
* 로드 밸런싱 및 고가용성을 위해 ONTAP에서 다중 LIF를 사용하십시오.
* ESXi 호스트와 ONTAP 시스템 간의 일관된 DNS 및 시간 동기화를 보장하십시오.
* NetApp 권장 ESXi 호스트 설정을 적용하십시오. ONTAP tools for VMware vSphere가 이 설정을 적용해 줄 수 있습니다.
* 효율적인 백업 및 복구를 위해 ONTAP 스냅샷 복사본을 사용하십시오.
* RBAC 및 내보내기 정책을 사용하여 NFS 볼륨에 대한 액세스를 제한하십시오.
* 장애 조치 시나리오를 테스트하여 고가용성 및 재해 복구 구성을 검증합니다.


자세한 내용은 link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vsphere-datastores-nfs.html["VMware vSphere with ONTAP 모범 사례 가이드의 NFS 데이터스토어"^] 및 link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vsphere-settings.html["권장되는 ESXi 호스트 및 기타 ONTAP 설정"^]을 참조하십시오.



[[nfs-connectivity-best-practices]]
== NFS 연결 모범 사례

ESXi 호스트와 ONTAP 스토리지 간의 NFS 연결을 구성할 때는 다음 모범 사례를 따르십시오:

* ESXi 호스트와 ONTAP NFS LIF를 동일한 네트워크 세그먼트에 배치하거나 적절한 라우팅이 이루어지도록 하십시오.
* 전용 VLAN을 사용하여 NFS 트래픽을 격리하고 보호하십시오.
* 로드 밸런싱 및 장애 조치를 제공하기 위해 NFS용 ONTAP LIF를 여러 개 구성하십시오.
* ONTAP 내보내기 정책이 데이터스토어를 마운트하는 모든 ESXi 호스트에서 액세스를 허용하는지 확인하십시오.
* 모든 호스트에 NFS 데이터스토어를 마운트할 때 일관된 DNS 이름 또는 IP 주소를 사용하십시오.
*  `vmkping`을(를) 사용하여 각 ESXi 호스트에서 ONTAP LIF로의 연결을 테스트하십시오.


네트워크 설계 지침은 link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vsphere-network.html["네트워크 구성"^]을(를) 참조하십시오.



[[nfs-provisioning-best-practices]]
== NFS 프로비저닝 모범 사례

VMware 환경용 ONTAP에 NFS 데이터스토어를 프로비저닝할 때는 다음 모범 사례를 따르십시오:

* *ONTAP tools for VMware vSphere 사용*: vSphere와의 올바른 구성 및 통합을 보장하려면 ONTAP 툴을 사용하여 NFS 데이터스토어를 프로비저닝하십시오. link:vmw-nfs-otv10.html["ONTAP tools for VMware vSphere 사용하여 vSphere 8에 대한 NFS 데이터 저장소 구성"]을(를) 참조하십시오.
* *적절한 볼륨 유형을 선택하십시오*: 소규모 워크로드에는 FlexVol 볼륨을, 높은 확장성이 필요한 대규모 환경에는 FlexGroup 볼륨을 선택하십시오. link:vmw-vvol-nfs-migration-storage-options.html["저장 옵션"]을(를) 참조하십시오.
* *내보내기 정책 구성*: 승인된 ESXi 호스트 또는 IP 범위로 액세스를 제한합니다.
* *씬 프로비저닝 활성화*: 공간 활용을 최적화하고 용량을 모니터링하여 오버커밋을 방지합니다.
* *스냅샷 예약 설정*: 보존 요구 사항에 따라 스냅샷 예약 크기를 조정하십시오.
* *여러 개의 LIF 사용*: 로드 밸런싱 및 고가용성을 위해 데이터스토어를 여러 LIF에 분산합니다.
* *용량 및 성능 모니터링*: 병목 현상을 방지하기 위해 데이터 저장소 사용량 및 성능 지표를 정기적으로 확인하십시오.




[[nconnect-recommendations]]
== nConnect 권장 사항

nConnect는 NFS 데이터 저장소당 여러 개의 TCP 연결을 허용하여 고속 네트워크 인터페이스 카드를 더 효율적으로 활용함으로써 처리량을 향상시킵니다.

* ESXi 8.0 업데이트 1에서는 NFSv3 데이터스토어용 nConnect가 도입되었으며, ESXi 8.0 업데이트 2에서 정식 출시되었습니다. ESXi 8.0 업데이트 3에서는 NFSv4.1용 nConnect가 추가되었습니다.
* 기본 설정은 데이터 저장소당 하나의 연결입니다. 기본적으로 데이터 저장소당 최대 4개의 연결을 설정할 수 있으며,  `/NFS/MaxConnectionsPerDatastore`고급 설정을 통해 최대 8개까지 늘릴 수 있습니다. 일반적으로 기본 최대값을 늘릴 필요는 없습니다.
* ESXi는 마운트된 모든 데이터스토어에 걸쳐 호스트당 최대 256개의 NFS 연결을 지원하며, 각 nConnect 연결은 해당 총 연결 수에 포함됩니다.
* vMotion의 성능 문제를 방지하려면, vSphere 클러스터의 모든 호스트에서 NFS 데이터스토어에 대해 동일한 수의 연결을 사용하십시오.
* 프로덕션 환경에서 대규모 변경을 수행하기 전에 사용자 환경에서 nConnect의 성능 영향을 테스트하십시오.


자세한 내용은 link:vmw-vsphere8-nfs-nconnect.html["NFS v3 데이터 저장소에서 nConnect를 사용하여 데이터 저장소 성능 개선"] 및 Broadcom KB 문서 link:https://knowledge.broadcom.com/external/article/313464/support-for-nconnect-feature-added-in-es.html["NFS 클라이언트 - ESXi에서의 nConnect 기능 지원"^]를 참조하십시오.



[[security-features]]
== 보안 기능

ONTAP은 VMware 환경의 NFS 데이터스토어에 대해 다음과 같은 보안 기능을 제공합니다:

* *내보내기 정책*: 허용된 호스트, IP 주소 또는 서브넷을 지정하여 NFS 볼륨에 대한 액세스를 제어합니다.
* *Kerberos 인증*: Kerberos(krb5, krb5i, krb5p)를 사용하는 NFSv4.1은 안전한 인증, 무결성 및 기밀성을 제공합니다.
* *역할 기반 액세스 제어(RBAC)*: 스토리지 리소스 관리를 위한 세부적인 권한을 부여합니다.
* *저장 데이터 암호화*: link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/index.html["저장된 데이터를 암호화합니다"^] 볼륨 또는 애그리게이트 수준에서 적용됩니다.
* *안전한 멀티 테넌시(multi-tenancy)*: SVM을 사용하여 워크로드를 격리합니다.
* *랜섬웨어 보호*: link:https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["ONTAP 자율 랜섬웨어 보호"^] 의심스러운 활동을 감지하고 복구 지점을 생성합니다.


자세한 내용은 link:https://docs.netapp.com/us-en/ontap/nfs-admin/index.html["ONTAP NFS 문서"^]을 참조하십시오.
