---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-otv.html 
keywords: vmware, getting, started, overview, netapp, otv, ontap, tools 
summary:  
---
= ONTAP tools for VMware vSphere 사용하여 가상 머신을 관리하는 방법에 대해 알아보세요.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere NetApp 스토리지를 사용하여 VM의 수명 주기 관리를 간소화합니다.  관리자는 vCenter Server에서 직접 스토리지를 관리하여 운영을 간소화하고 확장성을 향상시킬 수 있습니다.  VSC(Virtual Storage Console), VASA Provider, SRA(Storage Replication Adapter)와 같은 주요 구성 요소는 프로비저닝, 성능 모니터링, 재해 복구를 최적화합니다.



== 소개

이를 통해 관리자는 vCenter Server 내의 스토리지를 직접 관리하고 VMware 환경의 스토리지 및 데이터 관리를 간소화할 수 있습니다.  VMware vSphere Client 플러그인 도구는 vCenter Server 내부에서 실행할 필요 없이 플러그인 기능을 vSphere Client에 통합하도록 설계되었습니다.  이를 통해 플러그인을 분리하고 대규모 vSphere 환경에서 작동하는 플러그인의 확장이 가능해집니다.



== ONTAP 도구 구성 요소

* *가상 스토리지 콘솔(VSC)* VSC에는 vSphere 클라이언트와 통합된 인터페이스가 포함되어 있어 스토리지 컨트롤러를 추가하고, 데이터스토어를 프로비저닝하고, 데이터스토어의 성능을 모니터링하고, ESXi 호스트 설정을 보고 업데이트할 수 있습니다.
* *VASA 공급자* ONTAP 용 VMware vSphere APIs for Storage Awareness(VASA) 공급자는 VMware vSphere에서 사용하는 스토리지에 대한 정보를 vCenter Server로 전송하여 VMware Virtual Volumes(vVols) 데이터 저장소 프로비저닝, 스토리지 기능 프로필 생성 및 사용, 규정 준수 검증, 성능 모니터링을 지원합니다.
* *스토리지 복제 어댑터(SRA)* SRA를 활성화하고 VMware Site Recovery Manager(SRM)와 함께 사용하면 장애 발생 시 vCenter Server 데이터스토어와 가상 머신의 복구를 용이하게 하여 재해 복구를 위한 보호 사이트와 복구 사이트를 구성할 수 있습니다.


VMware용 NetApp ONTAP 도구에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["ONTAP tools for VMware vSphere 설명서"] .
