---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= ONTAP 에서 FC 기반 VMFS 데이터 저장소를 VCF 관리 도메인의 주 저장소로 사용합니다.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 사용 사례에서는 VMware Cloud Foundation(VCF) 관리 도메인의 기본 스토리지로 ONTAP에 FC 기반 VMFS 데이터스토어를 생성하는 절차를 설명합니다. 이 절차에는 필요한 구성 요소, 구성 및 배포 단계가 요약되어 있습니다.



[[introduction]]
== 소개

필요한 경우 vCenter에서 수행해야 하는 단계에 대한 외부 문서를 참조하고, 스토리지 구성 부분과 관련된 단계를 안내합니다.

vSphere 환경에서 ONTAP를 사용하여 기존 VMFS 데이터스토어(iSCSI 및 NVMe-oF 포함)를 변환하는 방법에 대한 자세한 내용은 link:vmw-vcf-mgmt-vmfs.html["vSphere 환경(VMFS 데이터스토어)을 VCF 관리 도메인으로 통합"]을 참조하십시오.


NOTE: VCF 5.2 릴리스에서는 기존 vSphere 8 환경을 VCF 관리 도메인으로 변환하거나 VCF VI 워크로드 도메인으로 가져오는 기능이 도입되었습니다. 이 릴리스 이전에는 VMware vSAN이 VCF 관리 도메인의 기본 스토리지로 사용할 수 있는 유일한 옵션이었습니다. NSX 컨트롤러 VM은 FC 기반 VMFS 데이터스토어에 배포하거나 이중 네트워크 스위치를 사용하여 단일 장애 지점을 방지하는 것이 좋습니다. 이러한 옵션을 사용할 수 없는 경우 vSAN을 사용하여 해당 VM을 호스팅하는 것을 고려하십시오.


NOTE: 이 솔루션은 NetApp ASA, AFF , FAS 포함한 FC 스토리지를 지원하는 ONTAP 플랫폼에 적용할 수 있습니다.



[[prerequisites]]
== 필수 조건

이 시나리오에서는 다음 구성 요소와 구성이 사용됩니다.

* FC 트래픽을 허용하도록 구성된 스토리지 가상 머신(SVM)이 있는 NetApp 스토리지 시스템입니다.
* FC 트래픽을 전달하고 SVM과 연관되는 FC 패브릭에 논리 인터페이스(LIF)가 생성되었습니다.
* FC 스위치에서 호스트 HBA 및 스토리지 대상에 대한 단일 이니시에이터-대상 구역 설정을 사용하도록 구역 설정이 구성되었습니다.


ONTAP 스토리지 시스템 구성에 대한 정보는 다음을 참조하세요.link:https://docs.netapp.com/us-en/ontap["ONTAP 9 문서"] 센터.

VCF 구성에 대한 자세한 내용은 link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation 문서"]을 참조하십시오.



[[deployment-steps]]
== 배포 단계



[[management-domain-default-cluster]]
=== 관리 도메인 - 기본 클러스터

VCF Installer 툴은 관리 도메인에 대해 FC 기반 VMFS, NFS v3 및 vSAN 데이터스토어를 지원합니다. 다음 단계에서는 ONTAP의 FC 기반 VMFS 데이터스토어를 주 스토리지로 사용하는 관리 도메인을 배포하는 절차를 설명합니다.

기존 vSphere 환경 사용에 대한 자세한 내용은 link:vmw-vcf-mgmt-vmfs.html["vSphere 환경(VMFS 데이터스토어)을 VCF 관리 도메인으로 통합"]을 참조하십시오.



[[management-domain-additional-cluster]]
=== 관리 도메인 - 추가 클러스터

추가 클러스터를 사용하여 관리 도메인을 확장하려면  https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["VCF 도메인에 SDDC 클러스터 추가"]을 참조하십시오.

관리 도메인에 추가 클러스터를 추가하는 단계는 대략 다음과 같습니다. * 호스트가 커미셔닝되고 네트워크 풀이 vCenter에 구성되어 있는지 확인합니다. * LUN이 ONTAP 스토리지 시스템에 프로비저닝되고 추가 클러스터의 호스트에 제공됩니다. * vCenter의 관리 도메인에서 새 SDDC 클러스터 생성을 만들고 마법사를 따라 추가 클러스터를 관리 도메인에 추가합니다.



[[additional-information]]
== 추가 정보

ONTAP 스토리지 시스템 구성에 대한 정보는 다음을 참조하세요.link:https://docs.netapp.com/us-en/ontap["ONTAP 9 문서"] 센터.

VCF 구성에 대한 자세한 내용은 link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation 문서"]을 참조하십시오.
