---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-supp-nfs-vvols-network.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, vvol, vvols, array, ontap tools, otv, sddc 
summary: ONTAP 스토리지 시스템에 대한 연결을 활성화하기 위해 VMware Cloud Foundation 관리 도메인의 ESXi 호스트에서 NFS 네트워킹을 구성합니다.  VLAN 분리를 통해 분산 포트 그룹을 만들고, 중복성을 위해 업링크 팀을 구성하고, 각 ESXi 호스트에 VMkernel 어댑터를 설정하여 장애 조치 기능을 위한 전용 NFS 경로를 설정합니다. 
---
= VCF VI 워크로드 도메인의 ESXi 호스트에서 NFS에 대한 네트워킹 구성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 스토리지 시스템에 대한 연결을 활성화하기 위해 VMware Cloud Foundation 관리 도메인의 ESXi 호스트에서 NFS 네트워킹을 구성합니다.  VLAN 분리를 통해 분산 포트 그룹을 만들고, 중복성을 위해 업링크 팀을 구성하고, 각 ESXi 호스트에 VMkernel 어댑터를 설정하여 장애 조치 기능을 위한 전용 NFS 경로를 설정합니다.

vSphere 클라이언트를 사용하여 VI 워크로드 도메인 클러스터에서 다음 단계를 수행합니다. 이 경우 vCenter Single Sign-On이 사용되므로 vSphere 클라이언트는 관리 및 워크로드 도메인에서 공통적입니다.



== 1단계: NFS 트래픽을 위한 분산 포트 그룹 만들기

네트워크에서 NFS 트래픽을 전송할 새로운 분산 포트 그룹을 만들려면 다음 단계를 완료하세요.

.단계
. vSphere 클라이언트에서 워크로드 도메인에 대한 *인벤토리 > 네트워킹*으로 이동합니다.  기존 분산 스위치로 이동하여 *새 분산 포트 그룹...*을 만드는 작업을 선택합니다.
. *새 분산 포트 그룹* 마법사에서 새 포트 그룹의 이름을 입력하고 *다음*을 클릭하여 계속합니다.
. *설정 구성* 페이지에서 모든 설정을 작성합니다. VLAN을 사용하는 경우 올바른 VLAN ID를 제공해야 합니다. 계속하려면 *다음*을 클릭하세요.
. *완료 준비* 페이지에서 변경 사항을 검토하고 *마침*을 클릭하여 새 분산 포트 그룹을 만듭니다.
. 포트 그룹이 생성되면 포트 그룹으로 이동하여 *설정 편집...* 작업을 선택합니다.
. *분산 포트 그룹 - 설정 편집* 페이지에서 왼쪽 메뉴의 *팀 구성 및 장애 조치*로 이동합니다. NFS 트래픽에 사용할 업링크의 티밍을 활성화하려면 *활성 업링크* 영역에 함께 있어야 합니다. 사용하지 않는 업링크를 *사용하지 않는 업링크*로 옮깁니다.
. 클러스터의 각 ESXi 호스트에 대해 이 프로세스를 반복합니다.




== 2단계: 각 ESXi 호스트에 VMkernel 어댑터 만들기

워크로드 도메인의 각 ESXi 호스트에 VMkernel 어댑터를 만듭니다.

.단계
. vSphere 클라이언트에서 워크로드 도메인 인벤토리의 ESXi 호스트 중 하나로 이동합니다. *구성* 탭에서 *VMkernel 어댑터*를 선택하고 *네트워킹 추가...*를 클릭하여 시작합니다.
. *연결 유형 선택* 창에서 *VMkernel 네트워크 어댑터*를 선택하고 *다음*을 클릭하여 계속합니다.
. *대상 장치 선택* 페이지에서 이전에 생성한 NFS용 분산 포트 그룹 중 하나를 선택합니다.
. *포트 속성* 페이지에서 기본값(활성화된 서비스 없음)을 유지하고 *다음*을 클릭하여 계속합니다.
. *IPv4 설정* 페이지에서 *IP 주소*, *서브넷 마스크*를 입력하고, 새로운 게이트웨이 IP 주소를 제공합니다(필요한 경우에만). 계속하려면 *다음*을 클릭하세요.
. *완료 준비* 페이지에서 선택 사항을 검토하고 *마침*을 클릭하여 VMkernel 어댑터를 만듭니다.




== 다음은 무엇인가요?

워크로드 도메인의 모든 ESXi 호스트에서 NFS에 대한 네트워킹을 구성한 후link:vmw-vcf-viwld-supp-nfs-vvols-storage.html["NFS vVols 에 대한 스토리지 구성"] .
