---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= VCF 워크로드 도메인의 주 스토리지로 ONTAP의 FC 기반 VMFS 데이터스토어 사용
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 사용 사례에서는 VMware Cloud Foundation(VCF) 워크로드 도메인의 기본 스토리지 솔루션으로 ONTAP에 Fibre Channel(FC) VMFS 데이터스토어를 설정하는 절차를 설명합니다. 이 절차에서는 필요한 구성 요소, 구성 단계 및 배포 프로세스를 요약합니다.



[[benefits-of-fibre-channel]]
== 파이버 채널의 이점

*고성능:* FC는 고속 데이터 전송률을 제공하므로 대량의 데이터에 빠르고 안정적으로 액세스해야 하는 애플리케이션에 이상적입니다.

*낮은 지연 시간:* 매우 낮은 지연 시간은 데이터베이스 및 가상화 환경과 같은 성능에 민감한 애플리케이션에 매우 중요합니다.

*신뢰성:* FC 네트워크는 내장된 중복성 및 오류 수정과 같은 기능을 갖추고 있어 견고성과 안정성이 뛰어난 것으로 알려져 있습니다.

*전용 대역폭:* FC는 스토리지 트래픽에 전용 대역폭을 제공하여 네트워크 혼잡 위험을 줄입니다.

NetApp 스토리지 시스템에서 파이버 채널을 사용하는 방법에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["FC를 사용한 SAN 프로비저닝"] .



[[scenario-overview]]
== 시나리오 개요

이 시나리오에서는 다음과 같은 상위 수준 단계를 다룹니다.

* FC 트래픽을 위한 논리 인터페이스(LIF)가 있는 스토리지 가상 머신(SVM)을 만듭니다.
* 배포될 호스트의 WWPN 정보를 수집하고 ONTAP 스토리지 시스템에 해당 이니시에이터 그룹을 생성합니다.
* ONTAP 스토리지 시스템에 FC 볼륨을 생성합니다.
* 생성된 FC 볼륨에 이니시에이터 그룹을 매핑합니다.
* FC 스위치에서 단일 이니시에이터-타겟 구역 설정을 활용합니다.  각 개시자마다 하나의 영역을 만듭니다(단일 개시자 영역).
+
** 각 영역에 대해 SVM에 대한 ONTAP FC 논리 인터페이스(WWPN)인 대상을 포함합니다.  SVM당 노드당 최소 2개의 논리적 인터페이스가 있어야 합니다.  물리적 포트의 WWPN을 사용하지 마세요.


* vCenter에서 vMotion 트래픽을 위한 네트워크 풀을 생성합니다.
* vCenter에서 워크로드 도메인에 사용할 호스트를 커미셔닝합니다.
* VCF Ops에서 FC 데이터스토어의 VMFS를 주 스토리지로 사용하여 워크로드 도메인을 배포합니다.



NOTE: 이 솔루션은 NetApp ASAr2, AFF 및 FAS를 포함하여 FC 스토리지를 지원하는 ONTAP 플랫폼에 적용됩니다.



[[prerequisites]]
== 필수 조건

이 시나리오에서는 다음 구성 요소와 구성이 사용됩니다.

* FC 포트가 FC 스위치에 연결된 ONTAP AFF, ASA 또는 FAS 스토리지 시스템.
* FC lifes로 생성된 SVM입니다.
* FC 스위치에 연결된 FC HBA가 있는 vSphere.
* FC 스위치에는 단일 이니시에이터-타겟 구역 설정이 구성됩니다.
* SVM 멀티패싱 정책이 액티브-액티브로 설정되어 있는지 확인하십시오.



NOTE: NetApp FC LUN에 대해 다중 경로를 권장합니다.



[[deployment-steps]]
== 배포 단계



[[vcf-workload-domain-default-cluster]]
=== VCF 워크로드 도메인 - 기본 클러스터

관리 도메인이 실행된 후에는 VCF 워크로드 도메인을 생성할 수 있습니다.

* VCF Ops UI를 사용합니다. vSphere 호스트는 vCenter에 커미셔닝되고 네트워크 풀이 구성됩니다. System Manager 또는 ONTAP API를 사용하여 LUN을 vSphere 호스트에 배포합니다.
* 기존 vSphere 환경을 새 워크로드 도메인으로 가져옵니다. ONTAP tools for VMware vSphere 또는 System Manager 또는 ONTAP API를 사용하여 VMFS 데이터스토어를 vSphere 클러스터에 배포할 수 있습니다.




[[vcf-workload-domain-additional-cluster]]
=== VCF 워크로드 도메인 - 추가 클러스터

추가 클러스터를 사용하여 워크로드 도메인을 확장하려면  https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["VCF 도메인에 SDDC 클러스터 추가"]을 참조하십시오.

워크로드 도메인에 추가 클러스터를 추가하는 단계는 다음과 같습니다. * 호스트가 커미셔닝되고 네트워크 풀이 vCenter에 구성되어 있는지 확인합니다. * ONTAP 스토리지 시스템에서 LUN이 프로비저닝되고 추가 클러스터의 호스트에 제공됩니다. * vCenter의 워크로드 도메인에서 새 SDDC 클러스터 생성을 만들고 마법사를 따라 추가 클러스터를 워크로드 도메인에 추가합니다.



[[additional-information]]
== 추가 정보

ONTAP 스토리지 시스템 구성에 대한 정보는 다음을 참조하세요.link:https://docs.netapp.com/us-en/ontap["ONTAP 9 문서"] 센터.

VCF 구성에 대한 자세한 내용은 link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation 문서"]을 참조하십시오.
