---
sidebar: sidebar 
permalink: vmware/vmw-vvol-nfs-migration-options.html 
keywords: netapp, vmware, nfs, migration, vvol, vvols, vmotion, storage vmotion, powercli 
summary: Storage vMotion, 콜드 마이그레이션, 스크립트 기반 마이그레이션 등 ONTAP를 사용하는 VMware 환경에서 vVols 데이터스토어에서 NFS 데이터스토어로 VM을 마이그레이션하는 옵션에 대해 알아보십시오. 
---
= vVols 데이터스토어에서 NFS 데이터스토어로의 마이그레이션 옵션
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP이 구축된 VMware 환경에서 vVols 데이터스토어에서 NFS 데이터스토어로 VM을 마이그레이션하는 옵션에 대해 알아보십시오. 여기에는 다운타임을 최소화하고 운영을 유지하기 위한 Storage vMotion, 콜드 마이그레이션, 스크립트 마이그레이션 등이 포함됩니다.

ONTAP이 있는 VMware 환경에서 vVols 데이터스토어에서 NFS 데이터스토어로 마이그레이션할 때 다음 옵션을 고려하십시오.

* *스토리지 vMotion*: 가상 머신이 실행되는 동안 vVols 데이터스토어에서 NFS 데이터스토어로 가상 머신 파일을 마이그레이션합니다. 두 데이터스토어 모두 가상 머신을 실행하는 ESXi 호스트에서 액세스할 수 있어야 합니다.
* *vMotion 및 스토리지 vMotion*: 소스 호스트와 대상 호스트가 스토리지를 공유하지 않는 경우 단일 작업으로 컴퓨팅 리소스와 데이터스토어를 모두 변경합니다.
* *콜드 마이그레이션*: 가상 머신의 전원을 끄고 vSphere Client에서 *마이그레이션* 옵션을 사용하여 NFS 데이터스토어로 이동합니다. 이 방법은 간단하지만 다운타임이 필요합니다.
* *백업 및 복원*: VM을 다른 데이터스토어로 복원할 수 있는 백업 애플리케이션을 사용하십시오. 이 방법은 소스 및 대상 데이터스토어에 동일한 호스트에서 액세스할 수 없는 경우에 유용합니다.
* *스크립트를 이용한 마이그레이션*: 대량 마이그레이션에는 PowerCLI 또는 기타 자동화 툴을 사용하십시오.


마이그레이션을 시작하기 전에 NFS 데이터스토어의 크기 지정, 구성 및 테스트가 올바르게 완료되었는지 확인하고 중요한 데이터를 백업하십시오.

PowerCLI 예제를 포함한 단계별 지침은 link:migrate-vms-to-ontap-datastore.html["VMware vSphere에서 ONTAP 데이터 저장소로 VM 마이그레이션"]을(를) 참조하십시오.



[[why-use-storage-vmotion-for-migration]]
== 마이그레이션에 스토리지 vMotion을 사용하는 이유

Storage vMotion은 다운타임 없이 VM 파일을 이동하므로 vVols 데이터스토어에서 NFS 데이터스토어로 VM을 마이그레이션하는 데 권장되는 방법입니다.

이 방법은 워크로드에 대한 중단을 최소화하고 애플리케이션을 계속 사용할 수 있는 상태에서 관리자가 VM을 이동할 수 있게 해줍니다. Storage vMotion은 VM 구성 및 메타데이터를 보존하며, 마이그레이션 중에 가상 디스크 형식을 유지하거나 변경할 수 있습니다.



[[concurrency-limits]]
== 동시성 제한

vCenter는 동시 마이그레이션 수를 제한합니다. 기본적으로 호스트는 최대 두 개의 Storage vMotion 작업을 동시에 실행할 수 있으며, 데이터스토어는 최대 8개의 작업에 참여할 수 있습니다. 추가 작업은 리소스가 확보될 때까지 대기열에 추가됩니다.

이러한 제한 사항을 고려하여 마이그레이션 배치 계획을 세우고 마이그레이션 중에 호스트, 네트워크 및 스토리지 사용률을 모니터링하십시오. 현재 제한 사항은 link:https://configmax.broadcom.com["VMware 구성 최대값"^]을(를) 참조하십시오.
