---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-migration.html 
keywords: vmware, getting, started, overview, netapp 
summary:  
---
= VMware vSphere에서 ONTAP 데이터 저장소까지의 VM에 대해 알아보세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware vSphere 관리자는 워크로드를 NetApp ONTAP 데이터 저장소로 마이그레이션하여 인프라를 개선할 수 있습니다.  ONTAP 스토리지 정책 기반 관리(SPBM)를 지원하는 동시에 VM 인식 스냅샷, 스토리지 효율적인 복제본, 원활한 vMotion 작업을 제공합니다.  vSAN, 레거시 스토리지에서 마이그레이션하거나 하이브리드 클라우드 배포를 구현하는 경우 ONTAP VMware 환경에 향상된 성능과 간소화된 스토리지 운영을 제공합니다.

이러한 마이그레이션을 통해 원활한 통합, 향상된 데이터 보호, 가상화 환경 관리의 더 큰 유연성이 가능해져 최소한의 가동 중지 시간으로 원활한 전환이 보장됩니다.



== 사용 사례

ONTAP 지원 데이터 저장소로 이전하는 것을 고려할 때 소스 및 대상 측면에서 마이그레이션에는 많은 옵션이 있습니다.

* 타사 스토리지 시스템(vSAN 포함)에서 ONTAP 데이터 저장소로 마이그레이션합니다.
* 동일한 vSphere 클러스터의 VM 마이그레이션
* 여러 vSphere 클러스터 간 VM 마이그레이션
* 동일한 SSO 도메인의 vCenter 서버 간 VM 마이그레이션
* 다양한 SSO 도메인의 vCenter 서버 간 VM 마이그레이션
* 데이터 센터 위치 간 VM 마이그레이션
* 타사 스토리지 시스템(vSAN 포함)에서 ONTAP 데이터 저장소로 마이그레이션합니다.
* 하이브리드 클라우드 환경에서 VM 마이그레이션


VMware 워크로드를 ONTAP 지원 데이터 저장소로 마이그레이션하는 방법에 대한 자세한 내용은 다음을 참조하세요.link:migrate-vms-to-ontap-datastore.html["VM을 ONTAP 데이터 저장소로 마이그레이션"] .
