---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-vmsc.html 
keywords: vmware, getting, started, overview, netapp, storage, metro, cluster 
summary:  
---
= MetroCluster 및 SnapMirror Active Sync를 사용하여 VMware 환경을 보호하는 방법에 대해 알아보세요.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
도메인 전체의 중단으로부터 VMware 환경을 보호하려면 고급 비즈니스 연속성이 필수적입니다.  NetApp 과 VMware는 NetApp MetroCluster, SnapMirror Active Sync, VMware vSphere Metro Storage Cluster(vMSC)와 같은 솔루션을 제공하여 워크로드 보호를 강화하고 높은 가용성을 보장합니다.



== 소개

VMware와 NetApp 제품에 내장된 가용성 외에도 랙, 빌딩, 캠퍼스 또는 도시와 같이 장애가 발생한 도메인에 분산된 워크로드를 더욱 보호하는 고급 구성을 제공합니다.



== NetApp MetroCluster

NetApp MetroCluster NetApp의 고가용성(HA) 기능을 사용하여 컨트롤러 오류로부터 보호합니다.  MetroCluster 에는 SyncMirror 기술, CFOD(Cluster failover on demand), 하드웨어 중복성, 고가용성을 위한 지리적 분리 기능도 포함되어 있습니다.  SyncMirror 두 개의 플렉스에 걸쳐 데이터를 동기적으로 미러링합니다. 로컬 플렉스는 데이터를 적극적으로 제공하고 원격 플렉스는 대기 상태로 유지합니다.  컨트롤러, 스토리지, 케이블, 스위치, 어댑터 등 모든 MetroCluster 구성 요소에는 하드웨어 중복성이 있습니다.



== NetApp SnapMirror 액티브 싱크

NetApp SnapMirror Active Sync는 FCP 및 iSCSI SAN 프로토콜을 통해 데이터 저장소별 보호 기능을 제공하고, 우선 순위가 높은 워크로드 토폴로지를 선택적으로 보호합니다.  이 솔루션은 액티브-스탠비 MetroCluster 와 달리 로컬 및 원격 사이트 모두에 액티브-액티브 액세스를 제공합니다.  ONTAP 9.15.1부터 SnapMirror 액티브 동기화는 대칭적인 액티브/액티브 기능을 지원하여 양방향 동기 복제를 통해 보호된 LUN의 두 복사본 모두에서 읽기 및 쓰기 I/O 작업을 허용합니다.



== VMware vSphere Metro 스토리지 클러스터

VMware vSphere Metro Storage Cluster(vMSC)는 액티브-액티브 스트레치드 스토리지로 VMware HA를 향상시킵니다.  이 인증된 구성은 VM과 컨테이너를 장애로부터 보호합니다.  이는 vSphere 호스트 클러스터와 함께 확장된 스토리지 개념을 사용하여 달성됩니다.  이러한 호스트는 서로 다른 장애 도메인에 분산되어 있습니다.  NetApp MetroCluster 및 SnapMirror Active Sync 스토리지 기술은 보호 및 지원되는 스토리지 제품을 제공하는 데 사용됩니다.  NetApp 인증 솔루션인 vMSC를 활용하면 장애 도메인 전체에서 강력하고 탄력적인 IT 운영을 제공할 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware_vmsc_overview.html#continuous-availability-solutions-for-vsphere-environments["ONTAP 사용한 vSphere Metro 스토리지 클러스터"] . {nbsp}
