---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= ONTAP 에서 FC 기반 VMFS 데이터 저장소를 VCF 관리 도메인의 주 저장소로 사용합니다.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 사용 사례에서는 ONTAP 의 기존 FC 기반 VMFS 데이터 저장소를 VMware Cloud Foundation(VCF) 관리 도메인의 기본 스토리지로 사용하는 절차를 설명합니다.  이 절차에서는 필요한 구성 요소, 구성 및 배포 단계를 요약합니다.



== 소개

적절한 경우 VCF의 SDDC 관리자에서 수행해야 하는 단계에 대한 외부 문서를 참조하고, 스토리지 구성 부분에만 해당하는 단계를 참조합니다.

기존 FC 기반 vSphere 환경을 ONTAP 으로 변환하는 방법에 대한 정보는 다음을 참조하세요.link:vmw-vcf-mgmt-fc.html["vSphere 환경(FC 데이터 저장소)을 VCF 관리 도메인으로 변환"] .


NOTE: VCF 릴리스 5.2에서는 기존 vSphere 8 환경을 VCF 관리 도메인으로 변환하거나 VCF VI 워크로드 도메인으로 가져오는 기능이 도입되었습니다.  이 릴리스 이전에는 VMware vSAN이 VCF 관리 도메인의 주 스토리지에 대한 유일한 옵션이었습니다.


NOTE: 이 솔루션은 NetApp ASA, AFF , FAS 포함한 FC 스토리지를 지원하는 ONTAP 플랫폼에 적용할 수 있습니다.



== 필수 조건

이 시나리오에서는 다음 구성 요소와 구성이 사용됩니다.

* FC 트래픽을 허용하도록 구성된 스토리지 가상 머신(SVM)이 있는 NetApp 스토리지 시스템입니다.
* FC 트래픽을 전달하고 SVM과 연관되는 FC 패브릭에 논리 인터페이스(LIF)가 생성되었습니다.
* FC 스위치에서 호스트 HBA 및 스토리지 대상에 대한 단일 이니시에이터-대상 구역 설정을 사용하도록 구역 설정이 구성되었습니다.


ONTAP 스토리지 시스템 구성에 대한 정보는 다음을 참조하세요.link:https://docs.netapp.com/us-en/ontap["ONTAP 9 문서"] 센터.

VCF 구성에 대한 정보는 다음을 참조하세요.link:https://docs.vmware.com/en/VMware-Cloud-Foundation/index.html["VMware Cloud Foundation 문서"] .



== 배포 단계



=== 관리 도메인 - 기본 클러스터

초기 클러스터의 FC 주 저장소는 VCF 브라운필드 가져오기 도구에서만 지원됩니다.  VCF가 Cloud Builder 도구(릴리스 버전 5.2.x 이전)를 사용하여 배포된 경우 vSAN만 지원됩니다.

기존 vSphere 환경 사용에 대한 자세한 내용은 다음을 참조하세요. https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html["기존 vSphere 환경을 관리 도메인으로 변환"] 자세한 내용은.



=== 관리 도메인 - 추가 클러스터

관리 도메인의 추가 vSphere 클러스터는 다음 옵션을 사용하여 배포할 수 있습니다.

* vSphere 환경에 추가 클러스터를 두고 VCF 브라운필드 가져오기 도구를 사용하여 vSphere 환경을 관리 도메인으로 변환합니다. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-datastore.html["ONTAP tools for VMware vSphere"] https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["시스템 관리자 또는 ONTAP API"] VMFS 데이터스토어를 vSphere 클러스터에 배포하는 데 사용할 수 있습니다.
* SDDC API를 사용하여 추가 클러스터를 배포합니다.  vSphere 호스트에는 VMFS 데이터 저장소가 구성되어 있어야 합니다.  사용 https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["시스템 관리자 또는 ONTAP API"] LUN을 vSphere 호스트에 배포합니다.
* SDDC 관리자 UI를 사용하여 추가 클러스터를 배포합니다.  하지만 이 옵션은 버전 5.2.x까지만 VSAN 데이터 저장소를 생성합니다.




== 추가 정보

ONTAP 스토리지 시스템 구성에 대한 정보는 다음을 참조하세요.link:https://docs.netapp.com/us-en/ontap["ONTAP 9 문서"] 센터.

VCF 구성에 대한 정보는 다음을 참조하세요.link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["VMware Cloud Foundation 문서"] .
