---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-snapcenter.html 
keywords: netapp, vmware, getting, started 
summary:  
---
= VMware vSphere용 SnapCenter 플러그인을 사용하여 가상 머신의 백업 및 복원에 대해 알아보세요.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere 사용하면 VM, 데이터 저장소 및 VMDK 파일에 대한 빠르고 VM 일관성 있는 백업 및 복원 작업이 가능합니다.  이 VMware 플러그인은 SnapCenter 서버와 통합되어 SnapCenter 애플리케이션별 플러그인에 대한 애플리케이션 기반 백업 및 복원을 지원합니다.



== 문서 리소스

자세한 내용은 다음 설명서 리소스를 참조하세요.

* link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["SnapCenter Plug-in for VMware vSphere 설명서"]




== 솔루션 리소스

다음은 SnapCenter Plug-in for VMware vSphere 과 VM용 NetApp 백업 및 복구를 포함하는 3-2-1 백업 솔루션입니다.

기술 보고서:link:https://docs.netapp.com/us-en/netapp-solutions-cloud/vmware/vmw-hybrid-321-dp-scv.html["SnapCenter 플러그인과 NetApp Backup and Recovery for VMs를 사용한 VMware용 3-2-1 데이터 보호"^]

Tech ONTAP 블로그:link:https://community.netapp.com/t5/Tech-ONTAP-Blogs/3-2-1-Data-Protection-for-VMware-with-SnapCenter-Plug-in-and-BlueXP-backup-and/ba-p/446180["SnapCenter 플러그인과 NetApp Backup and Recovery for VMs를 사용한 VMware용 3-2-1 데이터 보호"]



== 비디오 자료

.SnapCenter Plug-in for VMware vSphere - 솔루션 전제 조건
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto]
.SnapCenter Plug-in for VMware vSphere - 배포
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto]
.SnapCenter Plug-in for VMware vSphere - 백업 워크플로
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto]
.SnapCenter Plug-in for VMware vSphere - 복원 워크플로
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto]
.SnapCenter - SQL 복원 워크플로
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto]