---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-hmc.html 
keywords: vmware, getting, started, overview, netapp, hybrid, multicloud, multi, cloud 
summary:  
---
= NetApp 및 VMware를 사용한 하이브리드 멀티클라우드 환경에 대해 알아보세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp 과 VMware가 온프레미스 인프라와 퍼블릭 클라우드 서비스를 통합하여 하이브리드 멀티클라우드 설정을 간소화하고, 워크로드 마이그레이션, 리소스 최적화, 환경 전반의 일관된 운영을 지원하는 방법을 알아보세요.



== 소개

이러한 접근 방식을 통해 기업은 작업 부하를 쉽게 마이그레이션하고, 리소스 사용을 최적화하고, 두 환경에서 일관된 운영을 유지할 수 있습니다.

VMware 및 NetApp 사용한 하이브리드 클라우드 시나리오에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/netapp-solutions-cloud/vmware/vmw-hybrid-overview.html#vmware-cloud-options-in-public-cloud["VMware를 활용한 NetApp 하이브리드 멀티클라우드 개요"^] .



== NetApp 사용한 VMware 배포 시나리오

이 섹션에서는 온프레미스와 퍼블릭 클라우드에서 VMware 환경에 대한 다양한 배포 옵션을 설명합니다.  각 클라우드 공급업체는 각자의 퍼블릭 클라우드 서비스 내에서 VMware 소프트웨어 정의 데이터 센터(SDDC) 및/또는 VMware 클라우드 재단(VCF) 스택을 지원합니다.

* *온프레미스 VMware*


온프레미스에서 NetApp 스토리지와 함께 VMware를 사용하면 강력하고 확장 가능하며 유연한 가상화 환경을 구축할 수 있습니다.  중복 제거, 압축, 효율적인 스냅샷과 같은 NetApp의 고급 데이터 관리 기능을 ONTAP 기반의 적절한 스토리지 시스템과 결합함으로써 고객은 자신에게 적합한 플랫폼을 선택할 수 있습니다.  이러한 조합은 가상화된 워크로드에 대해 높은 성능, 안정성 및 간소화된 관리를 보장하여 전반적인 데이터 센터 효율성을 향상시킵니다.

* *Azure VMware 솔루션*


Azure VMware Solution은 Microsoft Azure 퍼블릭 클라우드 내에서 완벽한 기능을 갖춘 VMware SDDC를 구현할 수 있는 하이브리드 클라우드 서비스입니다. Azure VMware 솔루션은 Microsoft에서 완벽하게 관리하고 지원하는 자체 솔루션으로, Azure 인프라를 활용하여 VMware에서 검증되었습니다. 즉, Azure VMware Solution을 배포하면 고객은 컴퓨팅 가상화를 위한 VMware ESXi, 하이퍼 컨버지드 스토리지를 위한 vSAN, 네트워킹 및 보안을 위한 NSX를 모두 이용할 수 있으며, Microsoft Azure의 글로벌 입지, 동급 최고의 데이터 센터 시설, 풍부한 네이티브 Azure 서비스 및 솔루션 생태계와의 근접성을 활용할 수 있습니다.

* *AWS의 VMware 클라우드*


AWS의 VMware Cloud는 기본 AWS 서비스에 대한 최적화된 액세스를 통해 VMware의 엔터프라이즈급 SDDC 소프트웨어를 AWS 클라우드에 제공합니다. VMware Cloud Foundation 기반의 VMware Cloud on AWS는 VMware의 컴퓨팅, 스토리지 및 네트워크 가상화 제품(VMware vSphere, VMware vSAN 및 VMware NSX)과 VMware vCenter Server 관리를 통합하여 전용의 탄력적 베어메탈 AWS 인프라에서 실행되도록 최적화되었습니다.

* *구글 클라우드 VMware 엔진*


Google Cloud VMware Engine은 Google Cloud의 고성능 확장형 인프라와 VMware Cloud Foundation 스택(VMware vSphere, vCenter, vSAN, NSX-T)을 기반으로 구축된 서비스형 인프라(IaaS) 제품입니다. 이 서비스를 통해 기존 VMware 워크로드를 온프레미스 환경에서 Google Cloud Platform으로 원활하게 마이그레이션하거나 확장하여 클라우드로 빠르게 전환할 수 있으며, 애플리케이션 재설계나 운영 재구축에 따른 비용, 노력 또는 위험 부담 없이 운영을 재구축할 수 있습니다. Google에서 판매 및 지원하는 서비스로, VMware와 긴밀히 협력하고 있습니다.
