---
sidebar: sidebar 
permalink: vmware/vmw-vcf-expand.html 
keywords: vmware, vcf, expand, supplemental, storage 
summary: 'VMware Cloud Foundation(VCF)은 VCF 관리 도메인과 가상 인프라(VI) 워크로드 도메인의 스토리지를 확장하기 위한 광범위한 보조 스토리지 옵션을 지원합니다.' 
---
= 보조 스토리지를 사용하여 VCF 환경의 스토리지 확장에 대해 알아보세요.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware Cloud Foundation(VCF)은 VCF 관리 도메인과 가상 인프라(VI) 워크로드 도메인의 스토리지를 확장하기 위한 광범위한 보조 스토리지 옵션을 지원합니다.

ONTAP tools for VMware vSphere NetApp 스토리지를 VCF 환경에 원활하게 통합하여 이러한 확장을 위한 효율적인 솔루션을 제공합니다.

ONTAP 도구는 데이터스토어의 설정 및 관리를 간소화하여 관리자가 vSphere Client에서 직접 스토리지를 프로비저닝하고 관리할 수 있도록 합니다.  ONTAP의 스냅샷, 복제, 데이터 보호와 같은 고급 기능은 VCF 환경 내에서 스토리지 성능, 효율성, 확장성을 향상시킵니다.



== 저장 용량 확장을 위한 지원 프로토콜

VCF 환경은 여러 가지 저장 프로토콜을 사용하여 확장할 수 있으며, 각각 고유한 이점과 사용 사례를 제공합니다.

다음 프로토콜을 사용하여 VCF 관리 도메인과 VI 워크로드 도메인의 스토리지를 확장할 수 있습니다.  VCF 배포에 보조 스토리지를 원활하게 통합하기 위해 사용자 환경에 가장 적합한 옵션을 선택하세요.

.iSCSI
표준 이더넷 네트워크를 사용하는 블록 기반 프로토콜입니다.  고성능, 유연성, 비용 효율적인 확장이 필요한 환경에 이상적입니다.

iSCSI는 VMFS 데이터 저장소에 널리 사용되며 스냅샷 및 복제와 같은 고급 ONTAP 기능을 지원합니다.

* *고성능:* 빠르고 효율적인 데이터 전송 속도와 낮은 지연 시간을 제공하는 고성능을 제공합니다.  까다로운 엔터프라이즈 애플리케이션과 가상화 환경에 이상적입니다.
* *관리 용이성:* 익숙한 IP 기반 도구와 프로토콜을 사용하여 스토리지 관리를 간소화합니다.
* *비용 효율성:* 기존 이더넷 인프라를 사용하므로 특수 하드웨어의 필요성이 줄어들고 조직에서 안정적이고 확장 가능한 스토리지 솔루션을 구축할 수 있습니다.


NetApp 스토리지 시스템에서 iSCSI를 사용하는 방법에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/san-admin/san-host-provisioning-concept.html["iSCSI를 사용한 SAN 프로비저닝"] .

.파이버 채널(FC)
전용 FC 네트워크를 사용하는 고속, 저지연 프로토콜입니다.  FC는 안정성, 전용 대역폭, 강력한 오류 수정 기능이 요구되는 미션 크리티컬 워크로드에 적합합니다.  일반적으로 기업 환경에서 VMFS 데이터 저장소에 사용됩니다.

* *고성능:* FC는 고속 데이터 전송률을 제공하므로 대량의 데이터에 빠르고 안정적으로 액세스해야 하는 애플리케이션에 이상적입니다.
* *낮은 지연 시간:* 매우 낮은 지연 시간은 데이터베이스 및 가상화 환경과 같은 성능에 민감한 애플리케이션에 매우 중요합니다.
* *신뢰성:* FC 네트워크는 내장된 중복성 및 오류 수정과 같은 기능을 갖추고 있어 견고성과 안정성이 뛰어난 것으로 알려져 있습니다.
* *전용 대역폭:* FC는 스토리지 트래픽에 전용 대역폭을 제공하여 네트워크 혼잡 위험을 줄입니다.


NetApp 스토리지 시스템에서 파이버 채널을 사용하는 방법에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["FC를 사용한 SAN 프로비저닝"] .

.NFS(네트워크 파일 시스템)
호스트 간에 파일을 쉽게 공유하고 관리할 수 있게 해주는 파일 기반 프로토콜입니다.  NFS는 설정이 간편하고 효율적으로 확장 가능하므로 유연한 파일 액세스가 필요한 가상화된 작업 부하 및 환경에 적합합니다.

ONTAP 과 vSphere는 관리 및 워크로드 도메인 모두에서 NFS 데이터 저장소를 지원합니다.

* *간단하고 사용하기 쉬움:* NFS는 설정과 관리가 간단하므로 빠르고 쉽게 파일을 공유해야 하는 환경에 매우 적합합니다.
* *확장성:* ONTAP의 아키텍처는 NFS가 효율적으로 확장되어 인프라를 크게 변경하지 않고도 증가하는 데이터 요구 사항을 지원할 수 있도록 해줍니다.
* *유연성:* NFS는 광범위한 애플리케이션과 작업 부하를 지원하므로 가상화된 환경을 포함한 다양한 사용 사례에 다양하게 활용할 수 있습니다.


자세한 내용은 다음을 참조하세요. link:vmw-vvf-overview.html["vSphere 8용 NFS v3 참조 가이드"] .

.NVMe/TCP
TCP/IP를 사용하여 표준 이더넷 네트워크에서 높은 성능과 낮은 지연 시간을 제공하는 최신 프로토콜입니다.  NVMe/TCP는 특수 하드웨어가 필요 없이 확장성과 비용 효율성을 제공하므로 까다로운 애플리케이션과 대규모 데이터 작업에 이상적입니다.

* *고성능:* 낮은 지연 시간과 높은 데이터 전송 속도로 뛰어난 성능을 제공합니다.  이는 까다로운 애플리케이션과 대규모 데이터 작업에 매우 중요합니다.
* *확장성:* 확장 가능한 구성을 지원하여 IT 관리자가 데이터 요구 사항이 증가함에 따라 인프라를 원활하게 확장할 수 있습니다.
* *비용 효율성:* 표준 이더넷 스위치에서 실행되며 TCP 데이터그램 내부에 캡슐화됩니다. 구현에 특별한 장비가 필요하지 않습니다.


NVMe의 이점에 대한 자세한 내용은 다음을 참조하세요. https://www.netapp.com/data-storage/nvme/what-is-nvme/["NVME란 무엇인가요?"] .



== 보조 저장소 추가를 위한 사용 사례

다음 사용 사례에서는 다양한 프로토콜과 구성을 사용하여 VCF 관리 도메인과 VI(가상 인프라) 워크로드 도메인에 보조 스토리지를 추가하는 방법을 보여줍니다.

* link:vmw-vcf-mgmt-supplemental-iscsi.html["iSCSI를 사용한 관리 도메인"]
* link:vmw-vcf-mgmt-supplemental-fc.html["FC를 사용한 관리 도메인"]
* link:vmw-vcf-viwld-supp-iscsi-vvols.html["vVols 를 사용한 가상 인프라 워크로드 도메인(iSCSI)"]
* link:vmw-vcf-viwld-supp-nfs-vvols.html["vVols (NFS)를 사용한 가상 인프라 워크로드 도메인"]
* link:vmw-vcf-viwld-supp-nvme.html["NVMe/TCP를 사용한 가상 인프라 워크로드 도메인"]
* link:vmw-vcf-viwld-supp-fc.html["FC를 사용한 가상 인프라 워크로드 도메인"]

