---
sidebar: sidebar 
permalink: vmware/vmware-smbc-cvt-smas.html 
keywords: NetApp Solutions, vMSC, Metro Storage Cluster, SnapMirror active sync, Business Continuity, SMBC, ONTAP Tools, AFD, SCV, iSCSI, backup, restore 
summary:  
---
= VMware vSphere Metro Storage Cluster를 사용하여 SM 액티브 동기화를 비대칭에서 대칭 액티브/액티브로 변환
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 문서에서는 VMware vSphere Metro Storage Cluster(VMSC)를 사용하여 SnapMirror 액티브 동기화를 비대칭에서 대칭 액티브/액티브로 변환하는 방법을 자세히 설명합니다.



== 개요

link:https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/["NetApp Snapmirror 액티브 싱크(SM 액티브 싱크)"]가상화된 환경에서 0 복구 시간 목표(RTO)와 0 복구 지점 목표(RPO)를 달성하기 위한 강력한 솔루션입니다.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware_vmsc_overview.html["VMware vSphere Metro 스토리지 클러스터(vMSC)"]는 여러 장애 도메인에 걸친 확장된 클러스터 솔루션으로, 가상 머신(VM)을 지리적으로 분리된 두 사이트에 분산시켜 한 사이트에 장애가 발생하더라도 지속적인 가용성을 제공합니다.

vMSC를 SM 액티브 동기화와 결합하면 두 사이트 간의 데이터 일관성과 즉각적인 장애 조치 기능이 보장됩니다.  이러한 설정은 어떠한 데이터 손실이나 가동 중지도 용납할 수 없는 임무 수행에 중요한 애플리케이션에 특히 중요합니다.

이전에 SnapMirror Business Continuity(SMBC)로 알려졌던 SM 액티브 싱크는 사이트 전체에 장애가 발생하더라도 비즈니스 서비스가 계속 운영될 수 있도록 하며, 보조 복사본을 사용하여 애플리케이션이 투명하게 장애 조치를 취할 수 있도록 지원합니다.  ONTAP 9.15.1부터 SM 액티브 동기화는 대칭적인 액티브/액티브 기능을 지원합니다.  대칭적 액티브/액티브는 양방향 동기 복제를 통해 보호된 LUN의 두 복사본 모두에서 읽기 및 쓰기 I/O 작업을 수행할 수 있으므로 두 LUN 복사본 모두 로컬에서 I/O 작업을 수행할 수 있습니다.

이 문서에서는 VMware 스트레치 클러스터 환경에서 SM 액티브 동기화 비대칭 액티브/액티브를 SM 액티브 동기화 대칭 액티브/액티브로 변환하는 방법의 단계를 보여줍니다. 즉, SM 액티브 동기화를 자동 장애 조치 정책에서 자동 장애 조치-이중 정책으로 변환하는 것입니다.  System Manager 및 ONTAP Tools를 활용하여 SnapMirror Active Sync(SM-as)로 vMSC를 설정하는 방법에 대한 자세한 내용은 다음을 확인하세요.link:vmw-vmsc-with-smas.html["SnapMirror 활성 동기화를 갖춘 VMware vSphere Metro 스토리지 클러스터"] .



== 필수 조건

* NetApp 스토리지 시스템: Snapmirror 라이선스가 있는 두 개의 NetApp 스토리지 클러스터(소스 및 대상)가 있는지 확인하세요.
* 네트워크 연결: 소스 및 대상 시스템 간의 저지연 네트워크 연결을 확인합니다.
* 클러스터 및 SVM 피어링: 소스 및 대상 클러스터 간에 클러스터 피어링과 SVM(Storage Virtual Machine) 피어링을 설정합니다.
* ONTAP 버전: 두 클러스터 모두 동기 복제를 지원하는 ONTAP 버전을 실행하고 있는지 확인하세요.  SM Active Sync의 경우 ONTAP 9.15.1 이상이 필요합니다.
* VMware vMSC 인프라: 확장된 클러스터를 통해 하위 시스템이 여러 지역에 걸쳐 분포할 수 있으며, 두 사이트의 vSphere 클러스터에 단일하고 공통된 기반 인프라 리소스 세트를 제공합니다.  사이트 간의 네트워크와 스토리지를 확장합니다.
* NetApp SnapMirror 의 사용 편의성을 위해 ONTAP 도구 10.2 이상을 사용하십시오. 자세한 내용은 다음을 확인하세요.link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/release-notes/ontap-tools-9-ontap-tools-10-feature-comparison.html["ONTAP tools for VMware vSphere ."]
* 기본 클러스터와 보조 클러스터 사이에는 0 RPO Snapmirror 동기 관계가 존재해야 합니다.
* 0 RTO Snapmirror 관계를 생성하려면 대상 볼륨의 모든 LUN을 매핑 해제해야 합니다.
* Snapmirror Active Sync는 SAN 프로토콜만 지원합니다(NFS/CIFS는 지원하지 않음).  일관성 그룹의 어떤 구성 요소도 NAS 액세스를 위해 마운트되지 않았는지 확인하세요.




== 비대칭 SM 액티브 싱크에서 대칭 SM 액티브 싱크로 변환하는 단계

아래 예에서 selectrz1은 기본 사이트이고 selectrz2는 보조 사이트입니다.

. 보조 사이트에서 기존 관계에 대한 SnapMirror 업데이트를 수행합니다.
+
....
selectrz2::> snapmirror update -destination-path site2:/cg/CGsite1_dest
....
. SnapMirror 업데이트가 성공적으로 완료되었는지 확인하세요.
+
....
selectrz2::> snapmirror show
....
. 모든 0 RPO 동기 관계를 일시 중지합니다.
+
....
 selectrz2::> snapmirror quiesce -destination-path site2:/cg/CGsite1_dest
....
. 모든 0 RPO 동기 관계를 삭제합니다.
+
....
selectrz2::> snapmirror delete -destination-path site2:/cg/CGsite1_dest
....
. 소스 SnapMirror 관계를 해제하지만 공통 스냅샷은 유지합니다.
+
....
selectrz1::> snapmirror release -relationship-info-only  true -destination-path svm0.1:/cg/CGsite1_dest                                           ".
....
. AutomatedFailoverDuplex 정책을 사용하여 0 RTO SnapMirror 동기 관계를 만듭니다.
+
....
selectrz2::> snapmirror create -source-path svm0.1:/cg/CGsite1 -destination-path site2:/cg/CGsite1_dest -cg-item-mappings site1lun1:@site1lun1_dest -policy AutomatedFailOverDuplex
....
. 기존 호스트가 기본 클러스터에 로컬인 경우 해당 호스트를 보조 클러스터에 추가하고 각 클러스터에 대한 해당 액세스 권한으로 연결을 설정합니다.
. 보조 사이트에서 원격 호스트와 연결된 igroup의 LUN 맵을 삭제합니다.
+
....
selectrz2::> lun mapping delete -vserver svm0 -igroup wlkd01 -path  /vol/wkld01/wkld01
....
. 기본 사이트에서 기존 호스트의 이니시에이터 구성을 수정하여 로컬 클러스터의 이니시에이터에 대한 근접 경로를 설정합니다.
+
....
selectrz1::> set -privilege advanced
selectrz1::*> igroup initiator add-proximal-vserver -vserver site1  -initiator iqn.1998-01.com.vmware:vcf-wkld-esx01.sddc.netapp.com:575556728:67 -proximal-vserver site1
....
. 새로운 호스트에 대한 새로운 igroup과 이니시에이터를 추가하고 로컬 사이트에 대한 호스트 친화성을 위해 호스트 근접성을 설정합니다.  igroup 복제를 활성화하여 구성을 복제하고 원격 클러스터의 호스트 지역을 반전합니다.
+
....
selectrz1::*> igroup modify -vserver site1  -igroup smbc2smas -replication-peer svm0.1
selectrz1::*> igroup initiator add-proximal-vserver -vserver site1 -initiator iqn.1998-01.com.vmware:vcf-wkld-esx01.sddc.netapp.com:575556728:67 -proximal-vserver svm0.1
....
. 호스트의 경로를 검색하고 호스트에 기본 클러스터의 스토리지 LUN에 대한 활성/최적화된 경로가 있는지 확인합니다.
. 애플리케이션을 배포하고 VM 워크로드를 클러스터 전체에 분산합니다.
. 일관성 그룹을 다시 동기화합니다.
+
....
selectrz2::> snapmirror resync -destination-path site2:/cg/CGsite1_dest
....
. 호스트 LUN I/O 경로를 다시 스캔하여 LUN에 대한 모든 경로를 복원합니다.

