---
sidebar: sidebar 
permalink: opennebula/opennebula-storage-types.html 
keywords: netapp, opennebula, ontap, storage, nfs, smb, cifs, iscsi, fc, nvme, content types, vm disks, backups, templates 
summary: OpenNebula는 NAS 프로토콜용 NFS 및 SMB와 SAN 프로토콜용 FC, iSCSI 및 NVMe-oF를 포함하여 ONTAP에서 여러 스토리지 유형을 지원합니다. 
---
= OpenNebula에 대해 지원되는 스토리지 유형
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
OpenNebula는 NetApp ONTAP에서 NAS의 경우 NFS 및 SMB, SAN의 경우 FC, iSCSI 및 NVMe-oF를 포함한 여러 스토리지 프로토콜을 지원합니다. 사용자는 기존 기술 수준과 요구 사항에 따라 적절한 스토리지 프로토콜을 선택할 수 있습니다. ONTAP가 제공하는 데이터 서비스를 사용하지 않을 계획이라면 FC, iSCSI, Infiniband 및 NVMe-oF 프로토콜을 사용하여 블록 스토리지를 제공하는 SANtricity 시스템을 고려해 볼 수 있습니다.

OpenNebula는 일반적으로 /var/lib/one/datastores 폴더에 마운트되거나 /etc/one/oned.conf 파일의 DATASTORE_LOCATION 속성에 정의된 위치에 마운트되는 데이터스토어를 사용합니다. 스토리지는 /etc/fstab 파일을 사용하거나, Automounter를 사용하여 동적으로 마운트하거나, 또는 환경에서 지원하는 다른 절차를 통해 마운트할 수 있습니다. 대부분의 폴더 권한은 oneadmin 사용자 및 그룹으로 설정되어 있습니다. 하이퍼바이저 호스트가 필요한 프로토콜을 사용하여 스토리지 시스템에 접근할 수 있는지 확인하십시오.

자동 마운터를 사용할 때는 상위 폴더의 제어권을 자동 마운터가 차지하는 문제를 방지하기 위해 직접 마운트를 사용하십시오. 직접 마운트를 생성하려면 /etc/auto.master.d/ 아래에 파일을 생성하십시오. 예를 들어, 다음 명령을 사용하여 one.autofs라는 파일을 생성하십시오:

[source, bash]
----
echo "/-    /etc/auto.one --timeout=60 --ghost" > /etc/auto.master.d/one.autofs
----
프런트엔드 서버는 이미지 데이터스토어에 접근할 수 있어야 합니다. 하이퍼바이저 호스트에 이미지 데이터스토어를 마운트하는 것은 선택 사항이지만 성능 향상을 위해 권장됩니다. 시스템 데이터스토어는 가상 머신 디스크를 호스팅하므로 하이퍼바이저 호스트에 마운트해야 합니다. 커널 및 파일 데이터스토어는 VM 커널, 램디스크 및 컨텍스트화 프로세스를 통해 VM에 필요한 기타 파일에 사용됩니다. 프런트엔드 서버와 하이퍼바이저 호스트 모두에 마운트할 수 있습니다. 백업 데이터스토어는 VM 백업에 사용되며 OpenNebula 클러스터의 모든 호스트에 마운트할 수 있습니다. KVM 호스트가 rsync의 경우 SSH, restic의 경우 SFTP를 통해 백업 데이터스토어 호스트에 접근할 수 있다면 다른 클러스터의 VM도 동일한 백업 데이터스토어를 사용할 수 있습니다. Veeam을 사용하는 경우 oVirtAPI를 사용할 수 있어야 합니다.



== NAS 프로토콜 지원

NAS 프로토콜(NFS 및 SMB)은 프런트엔드와 하이퍼바이저 호스트 간에 공유 파일 시스템을 지원합니다. ONTAP 스냅샷을 클라이언트에 표시하여 특정 시점의 데이터 복사본에 액세스할 수 있습니다. ONTAP FlexCache는 지리적으로 분산된 영역 내의 이미지 데이터 저장소에 사용할 수 있습니다. ONTAP NFS는 nConnect를 지원하여 세션당 여러 연결을 사용함으로써 성능을 향상시킵니다. 대용량 데이터 저장소(> 100TB)에 FlexGroup을 사용하는 경우, 부하를 여러 노드에 분산하기 위해 pNFS를 사용하는 것이 좋습니다. ONTAP 클러스터의 각 컨트롤러마다 최소 하나의 데이터 lif를 구성해야 하며, 하이퍼바이저 호스트는 연결이 필요합니다.

모든 데이터 저장소 유형(이미지, 시스템, 커널 및 파일, 백업)은 NAS 프로토콜을 지원합니다.



== SAN 프로토콜 지원

엔터프라이즈 에디션에는 AFF 및 FAS 시스템에서 iSCSI 프로토콜과 함께 작동하는 NetApp 드라이버가 포함되어 있습니다. 다른 SAN 프로토콜(FC, InfiniBand 및 NVMe-oF)은 일반적으로 LVM 드라이버용으로 구성됩니다. LVM 씬 풀은 씬 프로비저닝 및 스냅샷 지원을 위해 가상 머신별로 생성됩니다. 하이퍼바이저 호스트는 스토리지 시스템에 연결되어 있어야 합니다. LVM 스토리지 유형을 사용하기 위해 클러스터 LVM 지원은 필요하지 않습니다.

NetApp 드라이버를 사용하려면 하이퍼바이저 호스트에서 iSCSI 세션과 다중 경로를 구성해야 합니다. LVM 드라이버의 경우 시스템 데이터스토어를 제외하고 논리 볼륨에 파일 시스템을 생성하고 마운트해야 합니다. 시스템 데이터스토어의 경우 볼륨 그룹 이름은 "vg-one-<datastore_id>" 형식으로 지정해야 하며, 여기서 <datastore_id>는 OpenNebula의 데이터스토어 숫자 식별자입니다. 모든 데이터스토어 유형(이미지, 시스템, 커널 및 파일, 백업)은 SAN 프로토콜을 지원합니다.



== NetApp ONTAP API 드라이버

OpenNebula의 기본 NetApp 통합은 ONTAP의 API를 사용하여 볼륨, LUN, 스냅샷 및 매핑을 자동으로 생성하고 관리합니다. 이 방법은 최상의 자동화 수준을 제공하며 수동 iSCSI 및 LVM 설정을 방지합니다. 자세한 내용은 link:https://docs.opennebula.io/7.0/integrations/storage_extensions/netapp/["OpenNebula 문서"]을(를) 참조하십시오.



== 저장 장치 유형 호환성 매트릭스

[cols="25% 15% 15% 15% 15% 15%"]
|===
| 데이터 저장소 유형 | NFS | SMB/CIFS | FC | iSCSI | NVMe-oF 


| 이미지 | 예 | 예 | 예  a| 
예^1^
| 예 


| 시스템 | 예 | 예 | 예  a| 
예^1^
| 예 


| 커널 및 파일 | 예 | 예 | 예 | 예 | 예 


| 백업 | 예 | 예 | 예 | 예 | 예 
|===
*참고사항:*

. NetApp 드라이버는 기본 ONTAP 기능을 활용하기 위해 iSCSI 프로토콜용 Enterprise 에디션에서 사용할 수 있습니다.




== OpenNebula 클러스터 스토리지 유형은 ONTAP에서 지원됩니다

NetApp ONTAP를 백엔드로 사용할 때 OpenNebula의 다양한 스토리지 유형에서 지원되는 기능을 비교한 표입니다.

[cols="30% 20% 20% 20%"]
|===
| 기능 | NetApp ONTAP API | LVM-thin | NFS/SMB 


| VM 디스크 | 예 | 예 | 예 


| 이미지 스토리지^1^ | 예 | 예 | 예 


| 라이브 스냅샷 | 예 | 예 | 예 


| VM 또는 이미지 복제 | 예 | 예 | 예 


| 증분 백업^2^ | 예 | 예 | 예 
|===
*참고사항:*

. 이미지 저장이란 OpenNebula 이미지 데이터 저장소의 백엔드를 사용하는 것을 의미합니다. LVM-thin 및 ONTAP API 메서드는 이미지 소스에서 블록 장치를 복사하거나 생성하는 작업을 포함합니다.
. 증분 백업은  `qcow2` 디스크(NFS/SMB) 또는 변경 내용 추적을 지원하는 블록 장치에서 작동합니다. OpenNebula NetApp ONTAP 드라이버는 롤링 스냅샷을 사용하여 증분 백업을 수행합니다.



NOTE: 증분 백업을 수행하려면  `nbd` 커널 모듈이 로드되어 있어야 합니다.
