---
sidebar: sidebar 
permalink: opennebula/opennebula-ontap-fc.html 
keywords: netapp, opennebula, lvm thin, fc, fibre channel, lvm, ontap, storage 
summary: 'ONTAP를 사용하여 OpenNebula용 Fibre Channel 기반 Logical Volume Manager (LVM) 데이터스토어를 구성합니다. 이 절차에는 다중 경로 구성, LUN 프로비저닝, igroup 설정, 공유 데이터스토어를 위한 볼륨 그룹 생성이 포함됩니다.' 
---
= OpenNebula용 ONTAP FC로 LVM Thin 구성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Fibre Channel 프로토콜을 사용하여 NetApp ONTAP와 함께 OpenNebula 호스트 간에 공유 스토리지를 위한 Logical Volume Manager (LVM) 데이터스토어를 구성합니다. 이 구성은 고성능 및 저지연의 블록 수준 스토리지 액세스를 제공합니다.



== 초기 가상화 관리자 작업

FC 연결을 위해 OpenNebula 호스트를 준비하고 스토리지 관리자에게 필요한 정보를 수집하려면 다음 초기 작업을 완료하십시오.

. 두 개의 HBA 인터페이스가 사용 가능한지 확인하십시오.
. 모든 OpenNebula 호스트에 multipath-tools가 설치되어 있고 부팅 시 자동으로 시작되는지 확인하십시오.
+
[role="tabbed-block"]
====
.Debian/Ubuntu
--
[source, shell]
----
apt list | grep multipath-tools
# If need to install, execute the following line.
apt-get install multipath-tools
# If /etc/multipath.conf is not present, first make sure the multipathd service is started.
systemctl enable --now multipathd
----
--
.RHEL/AlmaLinux
--
[source, shell]
----
dnf list installed | grep device-mapper-multipath
# If need to install, execute the following line.
dnf install device-mapper-multipath
# If /etc/multipath.conf is not present, first make sure the multipathd service is started.
systemctl enable --now multipathd
----
--
====
. 모든 OpenNebula 호스트의 WWPN을 수집하여 스토리지 관리자와 패브릭 영역 관리를 담당하는 관리자에게 제공하십시오.
+
[source, shell]
----
cat /sys/class/fc_host/host*/port_name
----




== 스토리지 관리자 작업

ONTAP 처음 사용하시는 경우, 시스템 관리자를 이용하시면 더욱 편리하게 사용하실 수 있습니다.

. SVM이 FC 프로토콜이 활성화된 상태로 사용 가능한지 확인하십시오. 따르다 link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["ONTAP 9 문서"].
. FC 전용으로 컨트롤러당 두 개의 LIF를 생성합니다. 생성된 FC LIF의 WWPN 주소를 수집하여 패브릭 조닝을 담당하는 관리자에게 제공합니다.
. igroup을 생성하고 호스트 FC 이니시에이터를 추가합니다. 일반적으로 OpenNebula 클러스터 하나당 하나의 igroup이 생성됩니다. Image 및 System 데이터스토어를 모두 지원하려면 프런트엔드 서버와 하이퍼바이저 호스트를 동일한 igroup에 포함하십시오.
. 원하는 크기의 LUN을 SVM에 생성하고 이전 단계에서 생성한 igroup에 제공합니다. ASA 시스템의 경우 보안 탭에서, AFF/ FAS 시스템의 경우 볼륨 보안 탭에서 랜섬웨어 방지 기능이 활성화되어 있는지 확인하십시오.
. LUN이 생성되었음을 가상화 관리자에게 알리십시오.




== 가상화 관리자 최종 작업

다음 작업을 완료하여 FC LUN을 OpenNebula에서 공유 LVM 데이터 저장소로 구성합니다.

. 모든 OpenNebula 서버에 SSH로 접속하여 각 호스트에서 다음 단계를 완료하십시오.
. SCSI 버스를 다시 스캔하여 새 LUN을 감지하려면 `rescan-scsi-bus.sh` 또는 `echo "- - -" > /sys/class/scsi_host/host*/scan`을(를) 실행하십시오.
. OpenNebula 호스트 모두에서  `lsblk -S` 또는 fdisk -l 명령을 사용하여 LUN이 표시되는지 확인하십시오. 생성된 LUN의 장치 이름(예: sde, sdf)을 기록해 두십시오.
.  `multipath -a /dev/<device_name>`을 실행하여 장치를 다중 경로 구성에 추가합니다. 그런 다음  `multipath -r`를 실행하여 다중 경로 구성을 다시 로드합니다.  `multipath -ll` 명령을 실행하여 다중 경로 구성을 확인합니다.
. 프런트엔드 서버 중 하나에 SSH로 접속하여 원하는 데이터 저장소 유형에 따라 구성 파일을 생성합니다. 전체 속성 목록은 https://docs.opennebula.io/7.0/product/cluster_configuration/san_storage/lvm_drivers/["OpenNebula LVM 문서"]를 참조하십시오. 샘플 파일은 아래와 같습니다.
+
[role="tabbed-block"]
====
.백업
--
.. Restic의 경우,


[listing]
----
$cat fc-restic.conf
NAME = "Backup-Restic-FC"
TYPE = "BACKUP_DS"

DS_MAD = "restic"
TM_MAD = "-"

RESTIC_PASSWORD = "<restic_password>"
RESTIC_SFTP_SERVER = "<backup server>"
----
.. Rsync의 경우


[listing]
----
$cat fc-rsync.conf
NAME = "Backup-Rsync-FC"
TYPE = "BACKUP_DS"

DS_MAD = "rsync"
TM_MAD = "-"

RSYNC_USER = "<rsync_user>"
RSYNC_HOST = "<backup server>"
----
--
.파일
[source, shell]
----
$cat fc-kernel.conf
NAME = "File-Kernel-FC"
TYPE = "FILE_DS"
DS_MAD = "fs"
TM_MAD = "local"
SAFE_DIRS = "/var/tmp/files"
----
.이미지
[source, shell]
----
$cat fc-image.conf
NAME = "Image-FC01"
TYPE = "IMAGE_DS"
DS_MAD = "fs"
TM_MAD = "fs_lvm_ssh"
DISK_TYPE = "block"
LVM_THIN_ENABLE = "yes"
----
.시스템
[source, shell]
----
$cat fc-system.conf
NAME = "System-FC02"
TYPE = "SYSTEM_DS"
TM_MAD = "fs_lvm_ssh"
DISK_TYPE = "block"
BRIDGE_LIST = "<space-separated list of OpenNebula hosts>" # If LUN not presented to frontend hosts
LVM_THIN_ENABLE = "yes"
----
====
. 실행 `onedatastore create <configuration file>`. 생성 후 반환되는 데이터 저장소 ID를 기록해 두세요.
+
[]
====
onedatastore 생성 fc-system.conf ID: 107

====
.  `vgcreate <vg_name> <multipath_device>` 명령을 사용하여 FC LUN에 볼륨 그룹을 생성합니다. Image 데이터스토어의 경우 볼륨 그룹 이름은 원하는 대로 지정할 수 있습니다. System 데이터스토어의 경우 볼륨 그룹 이름은  `vg-one-<datastore id>` 형식이어야 합니다. 이는 OpenNebula가 System 데이터스토어에 대한 올바른 볼륨 그룹을 식별하는 데 필요합니다. Backup/File/Image 데이터스토어를 생성하는 경우 다음 단계를 진행하십시오. System 데이터스토어의 경우 여기서 중지하십시오.
.  `lvcreate -l 100%FREE -n <logical volume name> <volume group name>` 명령을 사용하여 논리 볼륨 씬 풀을 생성합니다. 시스템 데이터스토어의 경우 OpenNebula에서 필요 시 LVM 씬 풀을 자동으로 생성합니다.
.  `mkfs.ext4 /dev/<volume group>/<logical volume>` 명령을 사용하여 논리 볼륨에 파일 시스템을 생성합니다. 시스템 데이터 저장소는 파일 시스템 생성이 필요하지 않습니다.
. 원하는 마운트 옵션으로 데이터스토어를 마운트하려면 /etc/fstab 또는 자동 마운트 구성을 업데이트하십시오. 기본 데이터스토어 위치는 /var/lib/one/datastores로 가정합니다.  `onedatastore show <datastore_id>`를 사용하여 확인할 수 있습니다. 그렇지 않은 경우 /etc/one/oned.conf의 DATASTORE_LOCATION 매개변수를 확인하십시오. 데이터스토어 위치에 <datastore_id> 폴더가 존재하는지 확인하십시오. 아래에 샘플 항목이 나와 있습니다:
+
[role="tabbed-block"]
====
./etc/fstab 사용
--
[source, shell]
----
/dev/<vg name>/<logical volume> /var/lib/one/datastores/<datastore_id> ext4 _netdev,noauto,x-systemd.automount,nofail 0 2
----
--
.automount 사용
--
[source, shell]
----
/var/lib/one/datastores/<datastore_id> -fstype=ext4,_netdev,noauto,x-systemd.automount,nofail,rw :/dev/<vg name>/<logical volume>
----
--
====
.  `mount -a` 또는  `systemctl reload autofs` 명령을 사용하여 데이터 저장소를 마운트합니다.
. `mount` 명령을 사용하여 데이터 저장소가 마운트되었는지 확인하고  `onedatastore show <datastore_id>` 명령을 사용하여 데이터 저장소 용량을 확인합니다.
. 데이터 저장소 폴더에 oneadmin 사용자 및 그룹의 소유권이 있는지 확인하십시오.  `chown -R oneadmin:oneadmin /var/lib/one/datastores/<datastore_id>` 명령어를 사용하여 권한을 조정하십시오.

