---
sidebar: sidebar 
permalink: openshift/osv-deployment-prerequisites.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift, OpenShift Virtualization, CNV, Container Native Virtualization, Red Hat OpenShift Virtualization 
summary: NetApp ONTAP 통한 Red Hat OpenShift 가상화 
---
= ONTAP 사용하여 Red Hat OpenShift Virtualization을 배포하기 위한 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 스토리지 시스템에 OpenShift 가상화를 설치하고 배포하는 데 필요한 요구 사항을 검토합니다.



== 필수 조건

* RHCOS 작업자 노드가 있는 베어 메탈 인프라에 설치된 Red Hat OpenShift 클러스터(버전 4.6 이상)
* VM의 HA를 유지하기 위해 머신 상태 점검 배포
* SVM이 올바른 프로토콜로 구성된 NetApp ONTAP 클러스터입니다.
* OpenShift 클러스터에 Trident 설치
* Trident 백엔드 구성이 생성되었습니다.
* Trident 프로비저너로 사용하여 OpenShift 클러스터에 구성된 StorageClass


위의 Trident 전제 조건은 다음을 참조하세요.link:osv-trident-install.html["Trident 설치 섹션"] 자세한 내용은.

* Red Hat OpenShift 클러스터에 대한 클러스터 관리자 액세스
* NetApp ONTAP 클러스터에 대한 관리자 액세스
* $PATH에 tridentctl 및 oc 도구가 설치되고 추가된 관리자 워크스테이션


OpenShift 가상화는 OpenShift 클러스터에 설치된 운영자에 의해 관리되므로 메모리, CPU 및 스토리지에 추가적인 오버헤드가 발생하며, 이는 클러스터의 하드웨어 요구 사항을 계획할 때 고려해야 합니다. 문서를 참조하세요 https://docs.openshift.com/container-platform/4.7/virt/install/preparing-cluster-for-virt.html#virt-cluster-resource-requirements_preparing-cluster-for-virt["여기"] 자세한 내용은.

선택적으로 노드 배치 규칙을 구성하여 OpenShift Virtualization 운영자, 컨트롤러 및 VM을 호스팅할 OpenShift 클러스터 노드의 하위 집합을 지정할 수도 있습니다.  OpenShift Virtualization에 대한 노드 배치 규칙을 구성하려면 설명서를 따르세요. https://docs.openshift.com/container-platform/4.7/virt/install/virt-specifying-nodes-for-virtualization-components.html["여기"] .

OpenShift Virtualization을 지원하는 스토리지의 경우, NetApp 특정 Trident 백엔드에서 스토리지를 요청하는 전용 StorageClass를 사용하는 것을 권장하며, 이는 전용 SVM에 의해 지원됩니다.  이를 통해 OpenShift 클러스터의 VM 기반 워크로드에 제공되는 데이터와 관련하여 다중 테넌시 수준이 유지됩니다.
